### PR TITLE
Make sure that only one error is sent for code actions

### LINKED ISSUE #3442: multiple errors on same line confuse code actions
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I am using lsp-grammarly. With a sentence like:

Here is a santence with moltiple mistakees.

if I click on the second or third mistakes, the code actions offered (either via sideline or code-actions right-mouse-click menu item) always belong to the first error.  If I write the sentence instead as:

Here is a santence 
with moltiple 
mistakees.

the problem disappears.  Happy to provide additional information.

### Steps to reproduce

requires lsp-grammarly

### Expected behavior

clicking on a given error should show code actions for that error, not others

### Which Language Server did you use?

text file

### OS

MacOS

### Error callstack

```emacs-lisp
no error messages
```

### Anything else?

that's it

### PR DESCRIPTION
**Pull request by yyoncho**
Fixes #3442

### CODE REVIEW

**Comment by ericdallo** [comment]
@yyoncho I think passing all line diagnostics is a good thing some times, at least for some servers like clojure-lsp, where to apply a code action you don't need to actually have your cursor exactly on the diagnostic but on the same line

**Comment by ericdallo** [comment]
Curious if other clients are doing that

**Comment by yyoncho** [comment]
I was wondering whether to make it configurable here. I havent checked it but I think that vscode is sending only the stuff under the cursor.

**Comment by ericdallo** [comment]
Yeah, maybe I'm skewed since I use a lot this "feature" of applying code actions without the need of having the cursor under exactly the diagnostics, but only on the same line, maybe more people feel the same, maybe we can go with that and check if anyone complains?

**Comment by yyoncho** [comment]
Ok, lets go this way and if it someone complains we will make it configurable.

**Pull request merged**
