### PR TITLE
lsp-modeline-code-action-mode: don't set/remove global-mode-string too much

### PR DESCRIPTION
**Pull request by kiennq**
We can just update `lsp--modeline-code-actions-string` instead of whole adding/remove from `global-mode-string`

### CODE REVIEW

**Comment by ericdallo** [comment]
Could you rebase it with master to CI run?
I fixed it on master a few minutes ago

**Comment by kiennq** [comment]
> Could you rebase it with master to CI run?
> I fixed it on master a few minutes ago

@ericdallo  Can you merge #1809? I don't have permission to push on master. And we need to trigger CI on pull request too

**Comment by ericdallo** [comment]
Done @kiennq

**Comment by yyoncho** [comment]
> @ericdallo Can you merge #1809? I don't have permission to push on master. And we need to trigger CI on pull request to

@ericdallo can we add push rights for every member? We have been like that for a long time and there were no issues with that so IMO ATM there is no reason to have a stricter policy.

**Pull request merged**
