### PR TITLE
Permit dynamic registration of semanticTokens capability

### PR DESCRIPTION
**Pull request by sebastiansturm**

### CODE REVIEW

**Comment by yyoncho** [comment]
How is supposed to test that?

**Comment by jsalzbergedu** [comment]
Lua-language-server, which dynamically registers semantic tokens, may aid in testing this.  (see issue #1846)

**Comment by sebastiansturm** [comment]
lua-language-server always tries to use dynamic registration for its semanticTokens capability (https://github.com/emacs-lsp/lsp-mode/issues/1846), so lsp-mode's current implementation of semantic highlighting should trigger the bug described in issue 1846 whereas this PR should not

**Comment by yyoncho** [comment]
@jsalzbergedu 

> Lua-language-server, which dynamically registers semantic tokens, may aid in testing this.

Thank would be great.

**Comment by yyoncho** [comment]
Can you resolve the conflicts?

**Comment by sebastiansturm** [comment]
I rebased on top of master, should be conflict-free now. @jsalzbergedu: could you please verify that this still resolves your lua highlighting issue? If you don't have the time for this, I'll follow your reproduction guide again, though an independent confirmation would of course be preferable

**Comment by jsalzbergedu** [comment]
Yes, that fixes my issue.

Thank you!

**Comment by yyoncho** [comment]
Thank you @sebastiansturm and @jsalzbergedu!

**Pull request merged**
