### PR TITLE
lsp-completion: support completion-lazy-hilit and quicker company-match

### PR DESCRIPTION
**Pull request by kiennq**
Currently `lsp-mode` doesn't highlight the candidates in the way `corfu` supports.
This PR adds:
- support for `completion-lazy-hilit` that can be used by `corfu` and alike completion UI. See https://github.com/minad/corfu/discussions/441
-  Also, in `lsp-completion--company-match` we can use `match-data` when possible, instead of going through matching again.
- Finally, in the work-around for #4192, we can just use `line-beginning-position` as a guard for cached start point. That would be better than having a take whole long substring and then dissect it for the first line.

### CODE REVIEW

**Comment by sebastiencs** [comment]
> Finally, in the work-around for https://github.com/emacs-lsp/lsp-mode/issues/4192, we can just use line-beginning-position as a guard for cached start point. That would be better than having a take whole long substring and then dissect it for the first line.

That seems good 

> support for completion-lazy-hilit 

Cool, I didn't know that `completion-lazy-hilit`

**Review by sebastiencs — APPROVED** [review]

**Comment by kiennq** [comment]
@yyoncho Do you think you can merge this change?

**Comment by jcs090218** [comment]
I've tried this patch, but the completion is no longer working. 🤔

**Comment by kiennq** [comment]
> I've tried this patch, but the completion is no longer working. 🤔

The completion via `company-mode`?

**Comment by jcs090218** [comment]
> The completion via company-mode?

Yes.

**Comment by kiennq** [comment]
I've tried with `emacs -Q` and it seems still working fine.
The company configuration looks like this

``` elisp
(setenv "LSP_USE_PLISTS" "1")
(setq company-idle-delay 0.05
      company-minimum-prefix-length 2
      company-selection-wrap-around t
      company-require-match 'company-explicit-action-p
      company-backends `(company-capf))
```

**Comment by jcs090218** [comment]
> I've tried with emacs -Q and it seems still working fine.
> The company configuration looks like this

Hmm... It's working this time. I am unsure why it didn't work the first time I tested it. Sorry for the noise.

**Review by jcs090218 — APPROVED** [review]

**Pull request merged**
