### PR TITLE
Fix formatting lsp-method-requirements

### LINKED ISSUE #1387: lsp-feature? does not seem to work, so indent-region-function gets set incorrectly
**Describe the bug**
In ruby files with solargraph, indent-region-function is getting set. It looks like this code is supposed to prevent that if the server does not support it:

https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L3226-L3228

Unfortunately, `(lsp-feature? "xxxx")` always returns something in ruby files (and others, it seems), regardless if what string you give it.

I'm on Emacs 27, if that matters.

**To Reproduce**

Open any file with lsp enabled and `M-: (lsp-feature? "textDocument/rangeFormatting")`. It should return nil, but does not.

**Expected behavior**
Should return nil

**Which Language Server did you use**
solargraph, ts-ls, likely others

**OS**
macos Catalina

**Error callstack**
None

### PR DESCRIPTION
**Pull request by aaronjensen**
Fixes #1387

### CODE REVIEW

**Comment by aaronjensen** [comment]
I don't know if this was intentional or not, but without it, the feature detection is broken for range formatting.

**Comment by yyoncho** [comment]
Thank you for contributing to `lsp-mode` and congrats for your first `lsp-mode` PR! :tada:

> I don't know if this was intentional or not, but without it, the feature detection is broken for range formatting.

it was a typo

CC @axelson

**Comment by aaronjensen** [comment]
Thank you for the quick merge!

**Comment by axelson** [comment]
It works! Thanks @aaronjensen and @yyoncho.

**Pull request merged**
