### PR TITLE
Update use-package declaration in official website! 

### PR DESCRIPTION
**Pull request by utkarsh181**

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]

**Comment by yyoncho** [comment]
There were complaints that it does not work in :init sections and it was moved before the use-package

**Comment by utkarsh181** [comment]
I have tested it with emacs-27.1 and emacs-master branch.

**Comment by yyoncho** [comment]
> There were complaints that it does not work in :init sections and it was moved before the use-package

I tested it now, and it seems like it is working fine.

**Comment by yyoncho** [comment]
Thank you!

**Pull request merged**
