### PR TITLE
File notifications

### LINKED ISSUE #331: provide facilities for sending DidChangeWatchedFiles notifications to the server
https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeWatchedFiles

### PR DESCRIPTION
**Pull request by yyoncho**
Fixes #331

- implemented facilities for handling file notifications

Example ussage:

(lsp-workspace-register-watch
 '(("/full/path/to/project/"
    ("**/*.java"
     "**/pom.xml"
     "**/*.gradle"
     "**/.project"
     "**/.classpath"
     "**/settings/*.prefs"))))

- I had a problems with running the tests with ert and on travis since the file
  notification are handled only when emacs is running in interactive
  mode (accept-process-output didn't work at all) and ert does not support
  running tests in that mode(the output is lost). Unfortunatelly the emacs
  instances that are running on travis are not compiled with file notification
  library and the tests cannot run on travis.
  The summary is that the tests for file notifications functions are disabled in
  travis but can be run locally if you have emacs compiled with file
  notification library with the following command:

  cast exect ert-runner -t no-win --no-win

- I haven't implemented the handling DidChangeWatchedFilesRegistrationOptions
  since the LSP server that I am using for testing (jdt) is not sending these
  notifications but instead the vscode-java plugin have predefined set of
  files (similar to the one in the example). Adding such handler is trivial once
  we have the functions for recursive file notifications.

### CODE REVIEW

**Comment by vibhavp** [comment]
Could you resolve the conflicts? Thanks.

**Comment by vibhavp** [comment]
Merging for now, we can figure out how to test this later.

**Comment by vibhavp** [comment]
@yyoncho The file-watch tests are failing on my machine too. Any idea what could be causing that?

Here's a log of ert-runner's output: https://gist.github.com/vibhavp/071a77f2fd399c37025a2b189e0f2ee5

**Comment by yyoncho** [comment]
@vibhavp can you check what is the value of  `file-notify--library`? Also, in order to run the tests you must pass "--no-win" param, for example:

`cask exec ert-runner --no-win -t no-win && echo passing`

Note that there is `ert-runner` bug which blocks displaying logs when the tests are started with "--no-win" param.

**Comment by MaskRay** [comment]
This may be reopened. I recently added the relevant support to ccls and tested it on vscode and coc.nvim, I think the expected interaction is:

* client sends `initialized`
* server sends `register/clientCapability` (RequestMessage)`
* client sends a response with `result: null`

```javascript
{"jsonrpc":"2.0","method":"initialized","params":{}}

{"jsonrpc":"2.0","method":"client/registerCapability","id":0,"params":{"registrations":[{"id":"didChangeWatchedFiles","method":"workspace/didChangeWat
chedFiles","registerOptions":{"watchers":[{"globPattern":"**/*"}]}}]}}

{"jsonrpc":"2.0","id":0,"result":null}
```

A notification of an added file looks like this:
```javascript
{"jsonrpc":"2.0","method":"workspace/didChangeWatchedFiles","params":{"changes":[{"uri":"file:///tmp/d/b.cc","type":1}]}}
```

**Pull request merged**
