### PR TITLE
Configure typescript-language-server to be default

### PR DESCRIPTION
**Pull request by yyoncho**

### CODE REVIEW

**Comment by yyoncho** [comment]
@seagle0128

**Comment by seagle0128** [comment]
Sorry for the late response due to the weekend!
Thanks for your work! I did reviews and testing in my env. One problem, `lsp-clients-typescript-server-args` should be set to `--stdio` by default IMO.

**Comment by yyoncho** [comment]
@seagle0128 thanks for the testing. I will redo my verification locally and update it accordingly.

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/lsp-mode/commit/df8bbdbc103135354040372c1123f0420118380b .

**Comment by seagle0128** [comment]
Thank you.
BTW, I'm glad to see doom-modeline in the screenshot :smile:

**Pull request merged**
