### PR TITLE
WIP: Add customization point for flycheck next-checkers

### PR DESCRIPTION
**Pull request by damienrg**
This PR introduces a customization point to let users specify a function that returns next-checkers for flycheck.

Related to https://github.com/flycheck/flycheck/pull/1836.

### CODE REVIEW

**Comment by yyoncho** [comment]
can you provide info on how it is supposed to be used? At a first sight, it looks like something that can live outside of lsp-mode.

**Comment by damienrg** [comment]
For example, user would have to do:

```lisp
(defun my-flycheck-lsp-next-checkers ()
  (pcase major-mode
    ('sh-mode '(sh-bash))
    ('lua-mode '(lua-selene))
    ('web-mode '(javascript-eslint))
    )
  )

(setq lsp-diagnostics-flycheck-next-checkers-function #'perso/flycheck-lsp-next-checkers)
```

**Comment by damienrg** [comment]
As discussed with @yyoncho I close the PR because the code could be done outside `lsp`.

**Comment by yyoncho** [comment]
Thank you. Still, it will be great if this ends up in our FAQ section once you are done with flycheck changes.

**Pull request closed without merging**
