### PR TITLE
[imp] default pylint to off

### PR DESCRIPTION
**Pull request by mpanarin**
https://github.com/palantir/python-language-server/pull/698

### CODE REVIEW

**Comment by seagle0128** [comment]
It does make sense and looks fine.

**Comment by yyoncho** [comment]
Merging based on @seagle0128's comment.

**Comment by AndreaOrru** [comment]
Even though this variable is set to nil, pylint sporadically runs. It's really annoying :(

**Comment by AndreaOrru** [comment]
I found that Pylint may still be run by `flycheck` as the next checker in chain even when you use `flake8`.

I solved it by doing:
```
(add-to-list 'flycheck-disabled-checkers 'python-pylint)
```

**Pull request merged**
