### PR TITLE
Exposed pyls configuration settings

### PR DESCRIPTION
**Pull request by yyoncho**

### CODE REVIEW

**Comment by yyoncho** [comment]
@noctuid

**Comment by noctuid** [comment]
Thanks! I believe the type should instead be something like `'(plist)` (defaults for `:key-type` and `:value-type` are symbol and sexp, which is correct here).

**Comment by yyoncho** [comment]
@noctuid fixed and force-pushed.

**Comment by cslux** [comment]
pyls also takes some extra arguments, maybe this should be supported too.

``` emacs-lisp
(defcustom lsp-clients-python-extra-arguments '()
  "Lsp client extra arguments."
  :group 'lsp-python
  :risky t
  :type 'list)

(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection 
                                   (push "pyls" lsp-clients-python-extra-arguments))
                  :major-modes '(python-mode)
                  :priority -1
                  :server-id 'pyls
                  :initialized-fn (lambda (workspace)
                                    (with-lsp-workspace workspace
                                      (lsp--set-configuration lsp-clients-python-settings)))
                  :library-folders-fn (lambda (_workspace)
                                        lsp-clients-python-library-directories)))
```

**Comment by yyoncho** [comment]
@cslux thanks for the review - can you take a look at the latest version?

**Comment by cslux** [comment]
@yyoncho Perfect, works! :+1:

**Pull request merged**
