### PR TITLE
Update options for lua-language-server

### PR DESCRIPTION
**Pull request by FollieHiyuki**
[schema.json](https://github.com/sumneko/vscode-lua/blob/master/setting/schema.json) for reference.
I also updated the version to 1.17.3 and changed some default values to the new ones.

### CODE REVIEW

**Comment by yyoncho** [comment]
Looks good to me from elisp perspective! @sunlin7 willing to take a look/test?

**Comment by FollieHiyuki** [comment]
1 note: the option `Lua.runtime.fileEncoding` does not work since upstream has typo on it (see the schema file). They got noticed so it will work in the future.
I currently use lua just to write basic config files, so I only need completion. Sorry for not being able to test it much.

**Comment by yyoncho** [comment]
> I currently use lua just to write basic config files, so I only need completion. Sorry for not being able to test it much.

No worries, I am inviting users who use actively use lua to hear their opinion on the changes.

**Review by yyoncho — APPROVED** [review]

**Comment by sunlin7** [comment]
Okay, I'll try this in my local, then update to you.

**Comment by sunlin7** [comment]
I try follow this change upgrading `lua-language-server` to `1.17.3`, but seems not work as preview version (on CentOS 7).
Disgrading to `1.17.2` and continue testing the options now.

**Comment by sunlin7** [comment]
I need more time for testing this change, there're high CPU (~120%) and memory (~3.4g) consuming issue and emacs stop response then.
I'm try my best to figure out the root cause.
image

**Comment by FollieHiyuki** [comment]
@sunlin7 I think you can change `lsp-lua-workspace-max-preload` back to  300 (the new default is 1000) and lower `lsp-diagnostics-workspace-rate`

**Comment by sunlin7** [comment]
@FollieHiyuki The high CPU and memory consumming issue already be reported as https://github.com/sumneko/lua-language-server/issues/439. 
For this PR, I also add some comments, please check them.

**Comment by FollieHiyuki** [comment]
I don't know what we could do here.
It appears to me that `lua-language-server` will check files in workspace based on the current directory, correct? So the solution is to manually change pwd or to use `projectile`? Correct me if I'm wrong

**Comment by sunlin7** [comment]
Hi @FollieHiyuki , The high CPU consumming issue should be NOT relate to current changes, it should be relate the initial workspace folder for `lsp-language-server`, I'll try my best to find the root cause.
For current changes, I submit serveral comments, please check them. Thanks.

**Comment by sunlin7** [comment]
Setting the `lsp-auto-guess-root` to `t` can resolve the high CPU consumming issue in my local, with this option, the `lsp-mode` will detect the root dir correctly (without this option, the root uri is  ~ home folder).

**Comment by yyoncho** [comment]
> Setting the `lsp-auto-guess-root` to `t` can resolve the high CPU consumming issue in my local, with this option, the `lsp-mode` will detect the root dir correctly (without this option, the root uri is ~ home folder).

lsp-mode won't pick automatically the HOME folder unless you have selected it in the initial import project dialog.

**Comment by sunlin7** [comment]
@yyoncho The high CPU consumming issue is my local issue, and yes, the HOME was a root dir for I had edit a "~/test.lua" in HOME dir for days ago. 
After I remove `~/.emacs.d/.lsp-session-v1`, then reopen a lua file, there is a prompt for selecting the root folder, every thing work like charm now.
Thanks.

**Comment by FollieHiyuki** [comment]
Thanks @sunlin7 for the comments. I fixed them (hopfully). Please review again.

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
Thank you!

**Pull request merged**
