### PR TITLE
Add client for Ansible

### PR DESCRIPTION
**Pull request by fredericgiquel**
Add `lsp-ansible` using https://github.com/ansible/ansible-language-server

### CODE REVIEW

**Comment by yyoncho** [comment]
Can you fix the CI:


> In toplevel form:
clients/lsp-ansible.el:162:1:Error: global/dynamic var ‘ansible’ lacks a prefix
make: *** [Makefile:43: unix-compile] Error 1

**Comment by fredericgiquel** [comment]
Unfortunately, I can't change the variable name. It's the name of the minor mode defined in the `ansible` package.

There is already an issue about the non-standard name of the minor mode https://github.com/k1LoW/emacs-ansible/issues/42
But no answer from the maintainer.

**Comment by yyoncho** [comment]
why? `(bound-and-true-p whatever)` works.

**Comment by fredericgiquel** [comment]
I remove the `defvar`. But the warning is still present with flycheck as we can see in this screenshot:
flycheck

I fear that the CI will fail again.

**Comment by yyoncho** [comment]
Thank you for contributing to `lsp-mode`!

**Pull request merged**
