### PR TITLE
lsp-capf: support company-quickhelp

### LINKED ISSUE #1513: Show doc tooltip of completion candidates using company-capf
When using company-lsp, the documentation of the selected candidate (not confirmed yet) will be shown in a hover frame besides if company-quickhelp or company-box is installed. As I saw in your documentation lately that company-capf is preferred, I switched to it. And the feature above stopped working..

After reading some relevant documentation, I realized that this is because (lsp-completion-at-point) function returns a plist without the :company-doc-buffer entry, which is used by company-quickhelp/box to fetch candidate documentation and render it.

Can this be implemented? I see it's not very hard, judging by the relevant code in company-lsp. I wanted to write it myself but I'm not very good at elisp and lsp...

### PR DESCRIPTION
**Pull request by kiennq**
Fix #1513 and potentially #1512

### CODE REVIEW

**Comment by yyoncho** [comment]
Thank you!

**Comment by liushihao456** [comment]
I'm afraid there is some bug. When I code in lsp-java, and select a completion candidate, the following appears in my minibuffer:
```
Error running timer ‘company-quickhelp--show’: (error "Company: backend company-capf error \"Wrong type argument: char-or-string-p, #s(hash-table siz$
                                                                                                                                                      
 *  **Parameters:**                                                                                                                                   
                                                                                                                                                      
     *  e                                                                                                                                             
 *  **Returns:**                                                                                                                                      
                                                                                                                                                      
     *  `true` (as specified by [Collection.add](jdt://contents/java.base/java.util/Collection.class?=sharewell/%5C/Library%5C/Java%5C/JavaVirtualMac$
 *  **Throws:**                                                                                                                                       
                                                                                                                                                      
     *  [ClassCastException](jdt://contents/java.base/java.lang/ClassCastException.class?=sharewell/%5C/Library%5C/Java%5C/JavaVirtualMachines%5C/ope$
     *  [NullPointerException](jdt://contents/java.base/java.lang/NullPointerException.class?=sharewell/%5C/Library%5C/Java%5C/JavaVirtualMachines%5C$
```
Having Toggled on debug-on-error, the following backtrace is shown:
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p #<hash-table equal 2/2 0x1fe3524cee9d>)                                           
  company-doc-buffer(#<hash-table equal 2/2 0x1fe3524cee9d>)                                                                                          
  apply(company-doc-buffer #<hash-table equal 2/2 0x1fe3524cee9d>)                                                                                    
  #f(compiled-function (fn xs) #<bytecode 0x29ef7e837e448>)(company-doc-buffer (#<hash-table equal 2/2 0x1fe3524cee9d>))                              
  -reduce-r-from(#f(compiled-function (fn xs) #<bytecode 0x29ef7e837e448>) (#("add(SimpleParkingEvent e) : boolean" 0 1 (lsp-completion-resolved t fa$
  #f(compiled-function (&rest args) #<bytecode -0x1536985b0f3a0e42>)(#("add(SimpleParkingEvent e) : boolean" 0 1 (lsp-completion-resolved t face (com$
  company-capf(doc-buffer #("add(SimpleParkingEvent e) : boolean" 0 1 (lsp-completion-resolved t face (completions-common-part) lsp-completion-prefix$
  apply(company-capf (doc-buffer #("add(SimpleParkingEvent e) : boolean" 0 1 (lsp-completion-resolved t face (completions-common-part) lsp-completion$
  company-call-backend-raw(doc-buffer #("add(SimpleParkingEvent e) : boolean" 0 1 (lsp-completion-resolved t face (completions-common-part) lsp-compl$
  company--force-sync(company-call-backend-raw (doc-buffer #("add(SimpleParkingEvent e) : boolean" 0 1 (lsp-completion-resolved t face (completions-c$
  company-call-backend(doc-buffer #("add(SimpleParkingEvent e) : boolean" 0 1 (lsp-completion-resolved t face (completions-common-part) lsp-completio$
  company-quickhelp--fetch-docstring(#("add(SimpleParkingEvent e) : boolean" 0 1 (lsp-completion-resolved t face (completions-common-part) lsp-comple$
  company-quickhelp--doc(#("add(SimpleParkingEvent e) : boolean" 0 1 (lsp-completion-resolved t face (completions-common-part) lsp-completion-prefix-$
```

Could you have a look, please?

**Comment by kiennq** [comment]
@liushihao456, can you take a protocol logging trace (`M-x lsp-toggle-trace-io`) when that happens?

**Comment by taigacute** [comment]
@kiennq  Is it possible to word wrap on doc buffer? its too long .
image
vim do it like this
image
maybe this question is about company or company-box?

**Comment by liushihao456** [comment]
@kiennq Here is the relevant log. taigacute seems to get it work, so maybe it's my own problem somewhere?
```
[Trace - 01:28:17 PM] Received response 'completionItem/resolve - (87)' in 25ms.                                                                      
Result: {                                                                                                                                             
  "textEdit": {                                                                                                                                       
    "newText": "add(${1:e})",                                                                                                                         
    "range": {                                                                                                                                        
      "end": {                                                                                                                                        
        "character": 19,                                                                                                                              
        "line": 54                                                                                                                                    
      },                                                                                                                                              
      "start": {                                                                                                                                      
        "character": 19,                                                                                                                              
        "line": 54                                                                                                                                    
      }                                                                                                                                               
    }                                                                                                                                                 
  },                                                                                                                                                  
  "insertTextFormat": 2,                                                                                                                              
  "insertText": "add",                                                                                                                                
  "sortText": "999999035",                                                                                                                            
  "documentation": {                                                                                                                                  
    "value": "Inserts the specified element into this priority queue.\n\n *  **Parameters:**\n    \n     *  e\n *  **Returns:**\n    \n     *  `true`$
    "kind": "markdown"                                                                                                                                
  },                                                                                                                                                  
  "detail": "PriorityQueue.add(SimpleParkingEvent e) : boolean",                                                                                      
  "kind": 2,                                                                                                                                          
  "label": "add(SimpleParkingEvent e) : boolean"                                                                                                      
}                           
```

**Comment by kiennq** [comment]
@taigacute I think this should be a question on `company-box`. It should render the documentation as it see fits

**Comment by kiennq** [comment]
@liushihao456 I'm working on a fix

**Comment by yyoncho** [comment]
Ah, I didn't saw that and pushed f0598d3

**Comment by liushihao456** [comment]
Thanks! It works now!

**Comment by yyoncho** [comment]
@taigacute report that in the company-box repo.

**Comment by taigacute** [comment]
got an error when use `typescript-lang-server`
```elisp
Debugger entered--Lisp error: (error "Failed to handle nil")
  signal(error ("Failed to handle nil"))
  error("Failed to handle %s" nil)
  lsp--render-element(nil)
  apply(lsp--render-element nil)
  #f(compiled-function (fn xs) #<bytecode 0x28af7e834d3c8>)(lsp--render-element (nil))
  -reduce-r-from(#f(compiled-function (fn xs) #<bytecode 0x28af7e834d3c8>) (#("log" 0 3 (lsp-completion-resolved t face (completions-common-part) lsp-completion-prefix-line "console." lsp-completion-start-point 85 lsp-sort-text "0" lsp-completion-item #<hash-table equal 8/8 0x1fe507c41879>))) (company-doc-buffer lsp--render-element lsp--capf-get-documentation))
  #f(compiled-function (&rest args) #<bytecode -0x2047661aa604e6f>)(#("log" 0 3 (lsp-completion-resolved t face (completions-common-part) lsp-completion-prefix-line "console." lsp-completion-start-point 85 lsp-sort-text "0" lsp-completion-item #<hash-table equal 8/8 0x1fe507c41879>)))
  company-capf(doc-buffer #("log" 0 3 (lsp-completion-resolved t face (completions-common-part) lsp-completion-prefix-line "console." lsp-completion-start-point 85 lsp-sort-text "0" lsp-completion-item #<hash-table equal 8/8 0x1fe507c41879>)))
  apply(company-capf (doc-buffer #("log" 0 3 (lsp-completion-resolved t face (completions-common-part) lsp-completion-prefix-line "console." lsp-completion-start-point 85 lsp-sort-text "0" lsp-completion-item #<hash-table equal 8/8 0x1fe507c41879>))))
  company-call-backend-raw(doc-buffer #("log" 0 3 (lsp-completion-resolved t face (completions-common-part) lsp-completion-prefix-line "console." lsp-completion-start-point 85 lsp-sort-text "0" lsp-completion-item #<hash-table equal 8/8 0x1fe507c41879>)))
  apply(company-call-backend-raw (doc-buffer #("log" 0 3 (lsp-completion-resolved t face (completions-common-part) lsp-completion-prefix-line "console." lsp-completion-start-point 85 lsp-sort-text "0" lsp-completion-item #<hash-table equal 8/8 0x1fe507c41879>))))
  company--force-sync(company-call-backend-raw (doc-buffer #("log" 0 3 (lsp-completion-resolved t face (completions-common-part) lsp-completion-prefix-line "console." lsp-completion-start-point 85 lsp-sort-text "0" lsp-completion-item #<hash-table equal 8/8 0x1fe507c41879>))) company-capf)
  company-call-backend(doc-buffer #("log" 0 3 (lsp-completion-resolved t face (completions-common-part) lsp-completion-prefix-line "console." lsp-completion-start-point 85 lsp-sort-text "0" lsp-completion-item #<hash-table equal 8/8 0x1fe507c41879>)))
  company-box-doc--fetch-doc-buffer(#("log" 0 3 (lsp-completion-resolved t face (completions-common-part) lsp-completion-prefix-line "console." lsp-completion-start-point 85 lsp-sort-text "0" lsp-completion-item #<hash-table equal 8/8 0x1fe507c41879>)))
  company-box-doc--show(0 #<frame Galaxy Emacs - global.js 0x7f942082d430>)
  #f(compiled-function () #<bytecode 0x2027e987fae15f3>)()
  apply(#f(compiled-function () #<bytecode 0x2027e987fae15f3>) nil)
  timer-event-handler([t 0 0 500000 nil #f(compiled-function () #<bytecode 0x2027e987fae15f3>) nil idle 0])
```

**Comment by kiennq** [comment]
Can you try with #1517

**Pull request merged**
