### PR TITLE
Expose the library folders for solargraph

### PR DESCRIPTION
**Pull request by yyoncho**
----

#

### CODE REVIEW

**Comment by yyoncho** [comment]
CC @arbox

**Comment by arbox** [comment]
@yyoncho,

thank you!

It's fully customizable, but I'd add `~/.rvm` and `~/.gem` to the default selection besides `~/.rbenv` from the very beginning.

**Comment by yyoncho** [comment]
> It's fully customizable, but I'd add `~/.rvm` and `~/.gem` to the default selection besides `~/.rbenv` from the very beginning.

Sure, I will update the PR before merging.

**Comment by arbox** [comment]
I confirm that it works as intended :+1:

**Pull request merged**
