### PR TITLE
Added client for Python-LSP-Server

### PR DESCRIPTION
**Pull request by AnselmC**
I added a client for the python-lsp-server implementation that is currently being maintained.
Not sure whether I should have to touch any other file.

### CODE REVIEW

**Comment by yyoncho** [comment]
I think that we already have a client for this https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-pylsp.el

(the entry in client.json that you are editing is for that server)

**Comment by AnselmC** [comment]
Ah I didn't see this. I guess it's missing from the documentation?
https://emacs-lsp.github.io/lsp-mode/page/languages/

**Comment by yyoncho** [comment]
> Ah I didn't see this. I guess it's missing from the documentation? https://emacs-lsp.github.io/lsp-mode/page/languages/

@ericdallo can you check why the entry is not generated from client.json? (it is there).

**Comment by ericdallo** [comment]
Yes, I can check later today

**Comment by ericdallo** [comment]
There was a missing configuration on mkdocs.yml, I fixed on 9865d3151

**Pull request closed without merging**
