### PR TITLE
chore: Add more tests for code locations in LSP features

### PR DESCRIPTION
**Pull request by necto**
Building on top of https://github.com/emacs-lsp/lsp-mode/pull/4502 (which is included in this branch at the moment, so it should be merged before the review of this PR), this change adds tests for additonal features that use code positions or ranges in the messages coming from LSP server:
- [X] Code action with embedded code edits
- [X] Gratuitous edit request coming from the LSP server (normally in response to a code-action command activation)
- [X] Code lens
- [X] Document formatting
- [X] Document highlight
- [X] Folding range
- [X] Find references
- [X] Go to definition / declaration
- [X] Inlay hints

As such, I consider it reaches the good enough coverage of the potentially affected code in the light of refactoring as outlined in https://github.com/emacs-lsp/lsp-mode/issues/4501

### CODE REVIEW

**Comment by jcs090218** [comment]
Some tests aren't passing. 🤔

**Comment by necto** [comment]
Yep, indeed. I'll look into why

**Comment by necto** [comment]
Fixed! :tada:

**Review by jcs090218 — APPROVED** [review]

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
Thank you!

**Pull request merged**
