### PR TITLE
watch all targets by default with rust-analyzer

### PR DESCRIPTION
**Pull request by brotzeit**
I think people expect this as a default configuration (https://github.com/brotzeit/rustic/issues/135)

### CODE REVIEW

**Comment by yyoncho** [comment]
@flodiebold

**Comment by flodiebold** [comment]
Isn't that what `lsp-rust-analyzer-cargo-all-targets` is for? This would be turned on by default on the server, so it makes sense to change the default to `t`, I think.

**Comment by brotzeit** [comment]
> Isn't that what lsp-rust-analyzer-cargo-all-targets is for? This would be turned on by default on the server, so it makes sense to change the default to t, I think.

I forgot about this one. Updated.

**Review by flodiebold — APPROVED** [review]
LGTM

**Comment by brotzeit** [comment]
Need a member's approval.

**Review by kiennq — APPROVED** [review]

**Review by jcs090218 — APPROVED** [review]

**Pull request merged**
