### PR TITLE
lsp--capf-cache: also clear cache on company completion start

### PR DESCRIPTION
**Pull request by kiennq**
Another potential fix for #1853

### CODE REVIEW

**Comment by kiennq** [comment]
@yyoncho Sorry for this but I think I need to revert this.
The `company-completion-started-hook` is running **after** `c-a-p-f`, thus it will always clear the cache when first getting from server.

**Comment by yyoncho** [comment]
> @yyoncho Sorry for this but I think I need to revert this.
The company-completion-started-hook is running after c-a-p-f, thus it will always clear the cache when first getting from server.

Then the option is to use advice on appropriate company function? 

CC @dgutov

**Comment by dgutov** [comment]
Have you tried `company-after-completion-hook`?

Speaking of using the cache, do you do that because some servers reply slowly? IIUC Eglot doesn't cache.

Another option would be to try and resurrect https://github.com/company-mode/company-mode/issues/975.

**Comment by kiennq** [comment]
> Have you tried `company-after-completion-hook`?

We've already used that, but it seems it's not enough. I.e,: in this bug, it seems the hook is not called.



> Speaking of using the cache, do you do that because some servers reply slowly? IIUC Eglot doesn't cache.

The server has an option of specifying if the returned completion items are all it can do, via `isIncomplete`.
In that case, querying more to server is pointless, and actually take time. So we cache the completion items in that case.

**Comment by yyoncho** [comment]
> Speaking of using the cache, do you do that because some servers reply slowly? IIUC Eglot doesn't cache.

Some servers return thousand of completion items and do not filter server side. Not using cache is not only slow but it is killing the garbage collector. And the protocol is designed to work this way.

**Comment by yyoncho** [comment]
@kiennq did you had a chance to check if this will work for us? https://github.com/company-mode/company-mode/issues/975

@dgutov is company-completion-started-hook called before capf the expected behaviour? If yes, probably there is a suitable function to use in combination with add-advice? 

@kiennq Alternatively, we may keep the modified tick in the cache and do not clean it the first time...

**Comment by dgutov** [comment]
> We've already used that, but it seems it's not enough. I.e,: in this bug, it seems the hook is not called.

Did you determine the exact reason why? It might be that the first time your completion function is called, it returns nil. And company doesn't enter completion. So simply avoiding caching the value nil could be one solution.

Another is in the linked issue. Where/how do you store the cache, BTW?

**Comment by yyoncho** [comment]
> Where/how do you store the cache, BTW?

we keep the cache in `defvar` when the appropriate from lsp point of view.

> It might be that the first time your completion function is called, it returns nil. 

We might return `nil` if there is no time to calculate the result due to user input. I guess this is causing the finished hook not to be called.

**Comment by dgutov** [comment]
> We might return nil if there is no time to calculate the result due to user input.

BTW, you should only do that if `non-essential` is `t`.

But it's a different issue: one if whether you save that `nil` value to the said defvar. You shouldn't.

But if you avoid caching any `nil` results at all, that aspect will be moot anyway.

**Comment by kiennq** [comment]
> But it's a different issue: a problem if you save that `nil` value to the said defvar. You shouldn't.
> 
> But if you avoid caching any `nil` results at all, that aspect will be moot anyway.

We've already not caching `nil` result already.

I think that may cause problem, since the completion hook is not called, the cache will never be cleaned.

**Comment by dgutov** [comment]
Not sure if I understand you here.

Are there situations where the after-completion-hook is not called after your completion function returns a non-empty table?

If you can show an example, I'll make sure to try and fix it.

**Comment by yyoncho** [comment]
> Are there situations where the after-completion-hook is not called after your completion function returns a non-empty table?
> 
> If you can show an example, I'll make sure to try and fix it.

we don't have a reproducer but it is happening.

**Comment by dgutov** [comment]
How about an execution trace? You can add some loud function `company-after-completion-hook`. E.g. one that calls `message`.

**Pull request merged**
