### PR TITLE
[lsp-rust] Add stopAtEntry for debugging lens

### PR DESCRIPTION
**Pull request by gagbo**
This ensures to get control at least once when running a single test

### CODE REVIEW

**Comment by yyoncho** [comment]
can we have that configurable?

**Comment by yyoncho** [comment]
Even better will be to have a list of default settings to append to the template. That way you will be able to change everything.

**Comment by gagbo** [comment]
I can do that for sure, but I really think that only the `stopAtEntry` is really necessary:
- all the arguments that are already present are computed from lsp-rust and I don't think it's wise to try to change that from user settings
- I think that maybe having an optional `dap-compilation(-dir)?` step added could be nice, but I found out recently with Cargo workspaces that it's not always trivial to find the correct compilation directory, so I'd rather leave it out as well.

**Comment by yyoncho** [comment]
I would say that we want to have any of these configurable: `MIMode` `miDebuggerPath` `externalConsole`(and probably more), WDYT?

(JFYI you may run a test in vterm using an external console).

**Comment by gagbo** [comment]
Seems all good :+1: , I ignored those MI settings because last time you told me that there was an issue with LLDB in cpptools anyway (and I just use Linux+GDB so I forgot).

**Comment by yyoncho** [comment]
> Seems all good  , I ignored those MI settings because last time you told me that there was an issue with LLDB in cpptools anyway (and I just use Linux+GDB so I forgot).

I havent investigated, but I suspect that the issue is exactly that - there is no way to specify that you want to run the tests with lldb.

**Comment by gagbo** [comment]
Is there a function is lsp-mode or dap-mode to safely merge plists ? I'm only using append here, but I'm not really sure what will happen if there are duplicate keys in the `defcustom` and the programmatically filled `list`. So I only added a warning in the defcustom docstring

**Review by yyoncho — APPROVED** [review]

**Pull request merged**
