### PR TITLE
Don't prompt about opening a web page if server can't be installed

### PR DESCRIPTION
**Pull request by thomasf**
With python and the pyls language server I get this prompt every time I open
any python file when I haven't already set up the language server. It is very
annoying so this patch demotes it from a yes or no prompt to a warn log message.

### CODE REVIEW

**Comment by thomasf** [comment]
I guess a possible downside with this change if is a newbie Emacs user don't know about the `*Messages*` buffer and don't know where to find the message/URL after it's being displayed in the mini buffer.

**Comment by thomasf** [comment]
As one would suspect, this is how it looks after the change:

image

**Comment by yyoncho** [comment]
> I guess a possible downside with this change if is a newbie Emacs user don't know about the `*Messages*` buffer and don't know where to find the message/URL after it's being displayed in the mini buffer.

We assume that lsp-mode users will at least know about it.

**Comment by thomasf** [comment]
I see an error, the message still has a question about opening the url. I'll fix it later this evening;

**Comment by yyoncho** [comment]
Thank you and congrats for your first `lsp-mode` PR!

**Pull request merged**
