### PR TITLE
Add reference card for essential commands

### PR DESCRIPTION
**Pull request by innerout**
This pull request introduces a basic reference card for essential commands 
and is inspired by cider as mentioned in #1172 .

### CODE REVIEW

**Comment by yyoncho** [comment]
Thank you for doing that, looks good to me! Let others share their opinion as well.

**Comment by chrbirks** [comment]
What about including the name of the function that each shortcut calls? It could help those who have conflicting shortcuts or want to write a hydra with some of these.

**Comment by innerout** [comment]
If I add too much text in a single command there is wrapping in the line then but I could make another reference card that contains the commands instead of the description.

**Comment by yyoncho** [comment]
@chrbirks we are using cider as a guide for this refcard. I guess the answer to your issue is using M-x describe-key.

**Comment by yyoncho** [comment]
Thank you!

**Pull request merged**
