### PR TITLE
Make sure that {} is presented when using plists

### LINKED ISSUE #1807: lsp-rust diagnostic is not updated when using lsp-use-plists
With `lsp-use-plists` enabled, the diagnostic information for `lsp-rust` is not updated.
Sample rust file:
``` rust
fn main() {
    let foobar = 1;
    let Foobar: i32 = 2;
    // foobar = 2;
}
```

After removing the comment (`//`), the diagnostic is not updated

### PR DESCRIPTION
**Pull request by yyoncho**
- fixes #1807

----

#

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]
:clap:

**Review by kiennq — APPROVED** [review]

**Comment by kiennq** [comment]
I will merge this, is there anything else blocking?

**Comment by ericdallo** [comment]
I think this is what was missing to enable plists on lsp-mode by default, so I think we are good and we can enable lsp-use-plists, right @yyoncho

**Comment by yyoncho** [comment]
> I think this is what was missing to enable plists on lsp-mode by default, so I think we are good and we can enable lsp-use-plists, right @yyoncho ?

We can. But IMO we should put a message that the user should recompile or delete and install again in a new session all lsp-mode related packages. It should be possible to turn that message off.

**Comment by ericdallo** [comment]
This PR doesn't do that @yyoncho? https://github.com/emacs-lsp/lsp-mode/pull/1861

**Comment by kiennq** [comment]
@yyoncho @ericdallo I've merged this PR. Looking forward to `lsp-use-plists` to be enabled by default.

**Pull request merged**
