### PR TITLE
Insert space to the lighter string for modeline

### PR DESCRIPTION
**Pull request by melito00**

### CODE REVIEW

**Comment by kiennq** [comment]
Do we need lighter for `lens-mode` in the first place?

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
I will approve this first since this is a valid changes. 

> Do we need lighter for lens-mode in the first place?

We should just remove it?

**Comment by nbfalcon** [comment]
I'd say that lighter is needed here because `lsp-lens-mode` provides a relatively important feature, so should show up by default, to be consistent with the rest of Emacs. 

Users of custom modelines like `doom-modeline`, `spaceline` by default won't see lighters anyway, and users of the standard modeline can use something like `use-package :diminish`.

From looking at `yasnippet`'s code, I see that they also have a space before the lighter.

**Comment by nbfalcon** [comment]
LGTM.

**Comment by nbfalcon** [comment]
Thank you for contributing to `lsp-mode`!

**Pull request merged**
