### PR TITLE
On windows, downcase filesystem paths

### PR DESCRIPTION
**Pull request by Gei0r**
Fix for https://github.com/emacs-lsp/lsp-ui/issues/226 and possibly #343

See also the corresponding [pull request on lsp-ui](https://github.com/emacs-lsp/lsp-ui/pull/227).

### CODE REVIEW

**Comment by Gei0r** [comment]
Maybe someone can help me figure out why the tests fail.
Because travis runs on linux, the commit should not change anything...

**Comment by yyoncho** [comment]
https://github.com/emacs-lsp/lsp-mode/blob/390a7ce22d00d204050f4e281176702f0b66ebaa/test/lsp-common-test.el#L31 test fakes that it is running under Windows .

**Comment by yyoncho** [comment]
Thanks a lot for this PR!  Can you rename the method to lsp--ajust-path/lsp--fix-path-casing/lsp--patch-filename (or at least use dashes in the name) ? I will merge it tomorrow when I am on my PC.

**Comment by Gei0r** [comment]
OK, I chose `lsp--fix-path-casing`.

Thank's for your patient support 💯

**Comment by yyoncho** [comment]
Thanks!

**Pull request merged**
