### PR TITLE
Proposed fix for tcp handling

### PR DESCRIPTION
**Pull request by yyoncho**
- added functions for checking and finding open ports

``` example registration
(lsp-register-client
 (make-lsp-client :new-connection (lsp-tcp-connection
                                   (lambda (port)
                                     `("php"
                                       ,(expand-file-name "~/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php")
                                       ,(format "--tcp-server=localhost:%s" port)
                                       "--memory-limit=4095M")))
                  :major-modes '(php-mode)
                  :server-id 'php-ls))
```

### CODE REVIEW

**Comment by yyoncho** [comment]
@tszg sorry for the delay, but it was crazy in lsp-mode these days. Can you test whether it works for you?

**Comment by tszg** [comment]
Great, now you can start the server properly.However, it will exit immediately after connection.
```
DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The xdebug extension is not loaded
DEBUG     Server listening on localhost:20000
NOTICE    PCNTL is not available. Only a single connection will be accepted
DEBUG     Connection accepted

Process php-ls stderr finished
```
 I suspect that there will be initial Settings after connection, but I don't know how to configure. This is the [configuration of vscode](https://github.com/felixfbecker/vscode-php-intellisense/blob/3b78c60524a8e18b4e7af99fabfff4430b4d9438/src/extension.ts#L111)

**Comment by tszg** [comment]
I set (setq lsp-print-io t) to get:
```

Quit [2 times]
>>> php-ls:6528 status:starting(async)
Content-Length: 1456



{
  "jsonrpc": "2.0",
  "method": "initialize",
  "params": {
    "processId": 16856,
    "rootPath": "e:/SourceCode/php/blog/",
    "rootUri": "file:///e:/SourceCode/php/blog/",
    "capabilities": {
      "workspace": {
        "applyEdit": true,
        "executeCommand": {
          "dynamicRegistration": false
        },
        "workspaceFolders": true
      },
      "textDocument": {
        "synchronization": {
          "willSave": true,
          "didSave": true,
          "willSaveWaitUntil": true
        },
        "documentSymbol": {
          "symbolKind": {
            "valueSet": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25
            ]
          },
          "hierarchicalDocumentSymbolSupport": true
        },
        "formatting": {
          "dynamicRegistration": true
        },
        "codeAction": {
          "dynamicRegistration": true
        },
        "completion": {
          "completionItem": {
            "snippetSupport": true
          }
        }
      }
    },
    "initializationOptions": null
  },
  "id": 5
}
php-ls::TCP has exited (finished)
Server php-ls:6528 status:starting exited with status closed. Do you want to restart it? (y or n) n

```

**Comment by yyoncho** [comment]
Lets move on gitter

**Comment by felixfbecker** [comment]
For editors, I would recommend to do what the VS Code extension does, which is start a TCP server on a port determined by the OS and tell the server to connect to that port.

https://github.com/felixfbecker/vscode-php-intellisense/blob/3b78c60524a8e18b4e7af99fabfff4430b4d9438/src/extension.ts#L87

**Comment by yyoncho** [comment]
Thanks, I had it working on Linux as a server, I will change it to work as a TCP client.

**Comment by yyoncho** [comment]
@tszg can you test the latest version? it is not polished (the process management is not 100% ready) but I believe it will connect properly.

```
(lsp-register-client
 (make-lsp-client :new-connection (lsp-tcp-server
                                   (lambda (port)
                                     `("php"
                                       ,(expand-file-name "~/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php")
                                       ,(format "--tcp=localhost:%s" port)
                                       "--memory-limit=4095M")))
                  :major-modes '(php-mode)
                  :server-id 'php-ls))
```

**Comment by tszg** [comment]
I now test it and I get:
```
Language server is connected on port 20000
progn: Wrong type argument: processp, (#<process php-ls> #<process TCP Server for: php-ls>)
```
In buffer, he does not work, lsp-print-io does not output any information.

**Comment by yyoncho** [comment]
@felixfbecker 
We changed the code to make the connection via -tcp=port and from the emacs internal process/connection explorer it looks like the connection is established but the language server does not respond to the initialization message. It happens only on windows and the LS logs are empty. Could you provide an advice now to debug it?

**Pull request closed without merging**
