### PR TITLE
Make `lsp-mode` a non-global mode, invoked by hooking into a major-mode.

### PR DESCRIPTION
**Pull request by vibhavp**
Other changes:
* Indentation is enabled for servers that support it.
* Symbols under point are highlighted.

### CODE REVIEW

**Comment by vibhavp** [comment]
@alanz could you see if this breaks anything with Haskell? `lsp-mode` is enabled with `(add-hook 'haskell-mode-hook #'lsp-mode)`.

**Comment by alanz** [comment]
checking now ...

**Comment by alanz** [comment]
I am getting something in messages about `global-lsp-mode` here: https://github.com/emacs-lsp/lsp-mode/blob/lsp-start/lsp-flycheck.el#L65

**Comment by alanz** [comment]
But it seems to startup ok. I am now receiving `textDocument/documentHighlight` requests, which is not in the capabilities my server sends back.

**Pull request merged**
