### PR TITLE
[lsp-magik] Add LSP client for Magik

### PR DESCRIPTION
**Pull request by krn-robin**
LSP client for the Magik programming language.
LSP server used is https://github.com/StevenLooman/magik-tools

### CODE REVIEW

**Comment by ericdallo** [comment]
Could you add documentation for the new client as mentioned [here](https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/) please?

**Comment by ericdallo** [comment]
I think you should add `lsp-magik` to `lsp-mode.el` at `lsp-client-packages` var

**Comment by krn-robin** [comment]
> Could you add documentation for the new client as mentioned [here](https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/) please?

Done

**Comment by krn-robin** [comment]
> I think you should add `lsp-magik` to `lsp-mode.el` at `lsp-client-packages` var

Done

**Review by ericdallo — APPROVED** [review]

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
Might want to update the changelog as well?

**Comment by yyoncho** [comment]
Can you resolve the conflicts?

**Comment by krn-robin** [comment]
> Can you resolve the conflicts?

Done!

**Comment by yyoncho** [comment]
Thank you!

**Pull request merged**
