### PR TITLE
Allow disabling timeouts

### PR DESCRIPTION
**Pull request by umanwizard**

### CODE REVIEW

**Comment by ericdallo** [comment]
@umanwizard do you have an example why you would like to disable the timeout?

**Comment by umanwizard** [comment]
Because requests in large Rust projects (e.g. https://github.com/MaterializeInc/materialize , which I work on as my day job) can take a few minutes to return when rust-analyzer’s cache is still cold.

Since one can cancel long-running requests with C-g anyway, I see no reason to have a timeout.

If you choose not to land this, I can just set the timeout to 9999, but that seems less elegant.

**Review by ericdallo — APPROVED** [review]
Makes sense to me, thanks!

**Comment by umanwizard** [comment]
Thanks @ericdallo ! Is any action needed from me in order to merge this?

**Review by jcs090218 — APPROVED** [review]

**Comment by ericdallo** [comment]
@umanwizard I was waiting for more input from other maintainers, could you add an entry on CHANGELOG? then I think we can merge this

**Comment by umanwizard** [comment]
Done!

**Comment by ericdallo** [comment]
Thank you!

**Pull request merged**
