### PR TITLE
Use :is-incomplete in lsp-make-completion-list

### PR DESCRIPTION
**Pull request by andrew-christianson**
This PR is the simple resolution to #1922.  I suspect there may be a more comprehensive solution involving `lsp-interface` but I have less insight into that area of this project

### CODE REVIEW

**Comment by yyoncho** [comment]
Thank you - it is typo when doing the lsp-mode lsp-protocol.el migration.

**Comment by yyoncho** [comment]
@andrew-christianson 

Do you think that we should provide an option(or code snippet) to allow disabling the completion results from one of the servers for pyright and ms-pyls case?

**Comment by andrew-christianson** [comment]
@yyoncho thanks for the quick merge.  I'd definitely like to have an option (or a snippet/example of how) to remove a specific capability from a server.  It'd be helpful for my msplys / mspyright case, but I think there could be other applications in areas where there are multiple competing/complementary language servers users might want to chose between.

I think `lsp--server-unregister-capability` is in the right direction, but I'm not sure if it's the best way to accomplish that

**Comment by yyoncho** [comment]
I think that the easiest the most straight forward way is to alter lsp-method-requirements and lsp--find-workspaces-for - we may introduce a key :disabled-if (or better name?) in lsp-method-requirements which is a list of functions. Unregister will work too but it should be combined with altering server capabilities. This is harder to implement becase sometimes a method is enabled when a particular provider is present and sometimes a method is enabled depending on a value in server capabilities so it will require strong protocol knowledge or ability to read elisp to know what to touch to disable the method.

**Comment by yyoncho** [comment]
> :disabled-if (or better name?) in lsp-method-requirements which is a list of functions

In could be different variable as well.

**Pull request merged**
