### PR TITLE
Bingo supports multi-root.

### PR DESCRIPTION
**Pull request by dsvensson**
Added Nov 29 '18:

https://github.com/saibing/bingo/issues/3#issuecomment-442793957

### CODE REVIEW

**Comment by dsvensson** [comment]
Actually, seems like there is some issue. The multi-root setup seems to be communicated correctly, but I'm having completion issues.

**Comment by yyoncho** [comment]
I will hold on the merge until we sort it out.

**Comment by yyoncho** [comment]
(cc @danielmartin )

**Comment by dsvensson** [comment]
I'll close this one for now as I think there might be more issues with bingo, or if I misunderstood it. It's just a oneliner anyway.

**Comment by yyoncho** [comment]
Just a heads up that we may redo the testing since there was an issue in lsp-mode code related to workspace folders.

**Pull request closed without merging**
