### PR TITLE
Add Move language client

### PR DESCRIPTION
**Pull request by dmakarov**
This PR adds very basic support for using move-analyzer LSP server in lsp-mode for developing in Move programming language https://github.com/move-language/move

### CODE REVIEW

**Comment by jcs090218** [comment]
You can use #4089 as a reference.

**Comment by dmakarov** [comment]
> You can use #4089 as a reference.

Thank you. Updated the PR. Should I add page/lsp-move.md or is it generated automatically?

**Review by jcs090218 — APPROVED** [review]
LGMT. :)

**Comment by dmakarov** [comment]
Would this PR be merged? There are some CI failures, but it looks like CI is broken on Windows, unrelated to this PR.

**Comment by jcs090218** [comment]
> Would this PR be merged? 

I usually leave PR open for a few days so other people can review it. 

> There are some CI failures, but it looks like CI is broken on Windows, unrelated to this PR.

Yeah, it's irrelevant. Don't worry about it! ;)

**Comment by dmakarov** [comment]
ping... maybe, it could be merged? (would love to update my lsp-mode package to include Move support)

**Comment by jcs090218** [comment]
All the tests have passed. We need to remove the "Required" rules for Emacs 26.3 since it's no longer being supported in lsp-mode. 🤔 

Merged! Thank you!

**Pull request merged**
