### PR TITLE
Add lsp-elixir.el

### PR DESCRIPTION
**Pull request by elxbarbosa**
up

### CODE REVIEW

**Comment by tarsius** [comment]
What about the `lsp-elixir` package from https://github.com/elixir-lsp/lsp-elixir.el, which is distributed on Melpa?

That obviously conflicts. Should it be removed from Melpa?

/cc @Trevoke

**Comment by Trevoke** [comment]
Thanks for bringing this up. As the elixir-ls community, we need to make a decision on this. We'll get back to you.

**Comment by Trevoke** [comment]
@tarsius yeah, it can be removed from melpa, thanks for pinging us and making sure we're involved and kept updated.

**Comment by tarsius** [comment]
Thanks!

**Pull request merged**
