### PR TITLE
Add client for Volar

### PR DESCRIPTION
**Pull request by jadestrong**
Add `lsp-volar` using https://github.com/johnsoncodehk/volar

### CODE REVIEW

**Comment by yyoncho** [comment]
can you resolve the conflicts?

**Comment by jadestrong** [comment]
@yyoncho The conflict has been resolved.

**Comment by yyoncho** [comment]
> @yyoncho The conflict has been resolved.

I will wait to see if the CI is fine and then I will proceed with the merge.

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
thank you!

**Comment by sethidden** [comment]
@jadestrong should the volar readme point to lsp-mode or still to your lsp-volar repo?
https://github.com/johnsoncodehk/volar/blob/master/README.md?plain=1#L32

**Pull request merged**
