### PR TITLE
lsp--capf-filter-candidates: using our own score to sort candidates

### PR DESCRIPTION
**Pull request by kiennq**
Since the built-in flex score is not so good to own liking, we should use our own fuzzy score function.
To be fair, here is the score of built-in `flex` scoring:
``` elisp 
(defun test-b (query candidates)
  (--> query
       ;; TODO: roll-out our own matcher if needed.
       ;; https://github.com/rustify-emacs/fuz.el seems to be good candidate.
       (let ((completion-styles '(flex))
             completion-regexp-list)
         (completion-all-completions it candidates nil (length it)))
       ;; completion-all-completions may return a list in form (a b . x)
       ;; the last cdr is not important and need to be removed
       (let ((tail (last it)))
         (if (consp tail) (setcdr tail nil))
         it)))
(pp (test-b "TH" `("TableHeaderUI" "TreeHomeAction"
                   "TransferHandler" "THREAD_POLICY_ID")))
(#("TableHeaderUI" 0 1
   (face completions-common-part completion-score 0.07692307692307693)
   5 6
   (face completions-common-part)
   6 7
   (face completions-first-difference))
  #("TreeHomeAction" 0 1
    (face completions-common-part completion-score 0.07142857142857142)
    4 5
    (face completions-common-part)
    5 6
    (face completions-first-difference))
  #("TransferHandler" 0 1
    (face completions-common-part completion-score 0.06666666666666667)
    8 9
    (face completions-common-part)
    9 10
    (face completions-first-difference))
  #("THREAD_POLICY_ID" 0 1
    (face completions-common-part completion-score 0.0625)
    1 2
    (face completions-common-part)
    2 3
    (face completions-first-difference)))
```
The score of `THREAD_POLICY_ID` is bellow other entries, which is not correct since it matched input `TH` at **the begining**.

And here is the score with our own `lsp--fuzzy-score`.
``` elisp
(defun test-a (query candidates)
  (--> (lsp--regex-fuzzy query)
       (-keep (lambda (cand)
                (when (string-match it cand)
                  (setq cand (copy-sequence cand))
                  (put-text-property 0 1 'match-data (match-data) cand)
                  cand))
              candidates)
       (-map (lambda (cand)
               (put-text-property
                0 1
                'completion-score (lsp--fuzzy-score query cand) cand)
               cand)
             it)))
(pp (test-a "TH" `("TableHeaderUI" "TreeHomeAction"
                   "TransferHandler" "THREAD_POLICY_ID")))
(#("TableHeaderUI" 0 1
   (match-data
    (0 6 0 1 5 6)
    completion-score 0.0463940651641776))
  #("TreeHomeAction" 0 1
    (match-data
     (0 5 0 1 4 5)
     completion-score 0.04479393708395793))
  #("TransferHandler" 0 1
    (match-data
     (0 9 0 1 8 9)
     completion-score 0.037399767197274295))
  #("THREAD_POLICY_ID" 0 1
    (match-data
     (0 2 0 1 1 2)
     completion-score 0.125)))
```
The scores now look much better and correctly favor `THREAD_POLICY_ID`.

For details, our own score is based on built-in `flex` score but adding a small penalty for hole in front of string. Thus it will boost the candidates which matched closer to start.
Also, I've used regex matcher borrowed from [`ivy`](https://github.com/abo-abo/swiper/), which will generate regex by inserting `.*` between each characters of query string.

### CODE REVIEW

**Comment by kiennq** [comment]
@yyoncho

**Comment by kiennq** [comment]
@yyoncho Can you help taking a look at this one?

**Comment by yyoncho** [comment]
I tested it and it works fine when the case is different at the beginning of the word but it fails for longer sequences.

**Comment by kiennq** [comment]
> I tested it and it works fine when the case is different at the beginning of the word but it fails for longer sequences.

Because it matched in the middle instead of beginning?
I've put the parameters so that the penalty for mismatch case is smaller than the penalty for matching further from begining.

For example, here is the completion score for test items:
``` elisp
(pp (test-a "gen" `("Generating" "generate"
                    "Thegenerate" "TheGenerate" "Theeegenerate")))
(#("Generating" 0 1
   (match-data
    (0 3 0 1 1 2 2 3)
    completion-score 0.2727272727272727))
  #("generate" 0 1
    (match-data
     (0 3 0 1 1 2 2 3)
     completion-score 0.375))
  #("Thegenerate" 0 1
    (match-data
     (3 6 3 4 4 5 5 6)
     completion-score 0.18328445747800587))
  #("TheGenerate" 0 1
    (match-data
     (3 6 3 4 4 5 5 6)
     completion-score 0.1717426150675521))
  #("Theeegenerate" 0 1
    (match-data
     (5 8 5 6 6 7 7 8)
     completion-score 0.13799346462951517)))
```

Would it make more sense to prioritize the case matching?
I would prefer putting the candidates that is more likely to match (regardless letter case) in front though. Should I make the case mismatch penalty an user option (or just `defvar`)?
Some thing like `lsp--fuzzy-score-case-mismatch-penalty`.

**Comment by kiennq** [comment]
@yyoncho Now you can set `lsp--fuzzy-score-case-sensitiveness` to value around `0.7` to get the case sensitive matches to be front.

**Comment by yyoncho** [comment]
You start typing `configBuilder` is at the top as the best match and when you type `g` it moves down. 

Screenshot at 2020-06-02 17-17-54

**Comment by kiennq** [comment]
@yyoncho What's the value from server for this completion?

I've tested with the bare candidates, and `configBuilder` definitely has higher score.
``` elisp
(defun test-a (query candidates)
  (--> (lsp--regex-fuzzy query)
       (-keep (lambda (cand)
                (when (string-match it cand)
                  (setq cand (copy-sequence cand))
                  (put-text-property 0 1 'match-data (match-data) cand)
                  cand))
              candidates)
       (-map (lambda (cand)
               (put-text-property
                0 1
                'completion-score (lsp--fuzzy-score query cand) cand)
               cand)
             it)))

(pp (test-a "config" `("ConfigFeature" "Configuration" "ConfigFunction" "configBuilder" "ConfigOverrides" "ConfigurationSpi")))
(#("ConfigFeature" 0 1
   (match-data
    (0 6 0 1 1 2 2 3 3 4 4 5 5 6)
    completion-score 0.38461538461538464))
  #("Configuration" 0 1
    (match-data
     (0 6 0 1 1 2 2 3 3 4 4 5 5 6)
     completion-score 0.38461538461538464))
  #("ConfigFunction" 0 1
    (match-data
     (0 6 0 1 1 2 2 3 3 4 4 5 5 6)
     completion-score 0.35714285714285715))
  #("configBuilder" 0 1
    (match-data
     (0 6 0 1 1 2 2 3 3 4 4 5 5 6)
     completion-score 0.46153846153846156))
  #("ConfigOverrides" 0 1
    (match-data
     (0 6 0 1 1 2 2 3 3 4 4 5 5 6)
     completion-score 0.3333333333333333))
  #("ConfigurationSpi" 0 1
    (match-data
     (0 6 0 1 1 2 2 3 3 4 4 5 5 6)
     completion-score 0.3125)))
```

**Comment by yyoncho** [comment]
```
[Trace - 06:01:35 PM] Received response 'textDocument/completion - (11)' in 62ms.
Result: {
  "items": [
    {
      "data": {
        "uri": "file:///home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java",
        "rid": "9",
        "pid": "0"
      },
      "textEdit": {
        "newText": "configBuilder",
        "range": {
          "end": {
            "character": 12,
            "line": 1058
          },
          "start": {
            "character": 8,
            "line": 1058
          }
        }
      },
      "insertTextFormat": 2,
      "insertText": "configBuilder",
      "sortText": "999999161",
      "kind": 6,
      "label": "configBuilder : SchemaGeneratorConfigBuilder"
    },
    {
      "data": {
        "uri": "file:///home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java",
        "rid": "9",
        "pid": "1",
        "decl_signature": "Lorg.eclipse.lsp4j.ConfigurationItem;"
      },
      "textEdit": {
        "newText": "ConfigurationItem",
        "range": {
          "end": {
            "character": 12,
            "line": 1058
          },
          "start": {
            "character": 8,
            "line": 1058
          }
        }
      },
      "insertTextFormat": 2,
      "insertText": "ConfigurationItem",
      "filterText": "ConfigurationItem",
      "sortText": "999999324",
      "detail": "org.eclipse.lsp4j.ConfigurationItem",
      "kind": 7,
      "label": "ConfigurationItem - org.eclipse.lsp4j"
    },
    {
      "data": {
        "uri": "file:///home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java",
        "rid": "9",
        "pid": "2",
        "decl_signature": "Lorg.eclipse.lsp4j.ConfigurationParams;"
      },
      "textEdit": {
        "newText": "ConfigurationParams",
        "range": {
          "end": {
            "character": 12,
            "line": 1058
          },
          "start": {
            "character": 8,
            "line": 1058
          }
        }
      },
      "insertTextFormat": 2,
      "insertText": "ConfigurationParams",
      "filterText": "ConfigurationParams",
      "sortText": "999999324",
      "detail": "org.eclipse.lsp4j.ConfigurationParams",
      "kind": 7,
      "label": "ConfigurationParams - org.eclipse.lsp4j"
    },
    {
      "data": {
        "uri": "file:///home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java",
        "rid": "9",
        "pid": "3",
        "decl_signature": "Lcom.fasterxml.jackson.databind.cfg.ConfigFeature;"
      },
      "additionalTextEdits": [
        {
          "newText": "\nimport com.fasterxml.jackson.databind.cfg.ConfigFeature;",
          "range": {
            "end": {
              "character": 47,
              "line": 7
            },
            "start": {
              "character": 47,
              "line": 7
            }
          }
        }
      ],
      "textEdit": {
        "newText": "ConfigFeature",
        "range": {
          "end": {
            "character": 12,
            "line": 1058
          },
          "start": {
            "character": 8,
            "line": 1058
          }
        }
      },
      "insertTextFormat": 2,
      "insertText": "ConfigFeature",
      "filterText": "ConfigFeature",
      "sortText": "999999372",
      "detail": "com.fasterxml.jackson.databind.cfg.ConfigFeature",
      "kind": 8,
      "label": "ConfigFeature - com.fasterxml.jackson.databind.cfg"
    },
    {
      "data": {
        "uri": "file:///home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java",
        "rid": "9",
        "pid": "4",
        "decl_signature": "Lcom.fasterxml.jackson.databind.cfg.ConfigOverrides;"
      },
      "additionalTextEdits": [
        {
          "newText": "\nimport com.fasterxml.jackson.databind.cfg.ConfigOverrides;",
          "range": {
            "end": {
              "character": 47,
              "line": 7
            },
            "start": {
              "character": 47,
              "line": 7
            }
          }
        }
      ],
      "textEdit": {
        "newText": "ConfigOverrides",
        "range": {
          "end": {
            "character": 12,
            "line": 1058
          },
          "start": {
            "character": 8,
            "line": 1058
          }
        }
      },
      "insertTextFormat": 2,
      "insertText": "ConfigOverrides",
      "filterText": "ConfigOverrides",
      "sortText": "999999372",
      "detail": "com.fasterxml.jackson.databind.cfg.ConfigOverrides",
      "kind": 7,
      "label": "ConfigOverrides - com.fasterxml.jackson.databind.cfg"
    },
    {
      "data": {
        "uri": "file:///home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java",
        "rid": "9",
        "pid": "5",
        "decl_signature": "Lcom.fasterxml.jackson.databind.cfg.ConfigOverride;"
      },
      "additionalTextEdits": [
        {
          "newText": "\nimport com.fasterxml.jackson.databind.cfg.ConfigOverride;",
          "range": {
            "end": {
              "character": 47,
              "line": 7
            },
            "start": {
              "character": 47,
              "line": 7
            }
          }
        }
      ],
      "textEdit": {
        "newText": "ConfigOverride",
        "range": {
          "end": {
            "character": 12,
            "line": 1058
          },
          "start": {
            "character": 8,
            "line": 1058
          }
        }
      },
      "insertTextFormat": 2,
      "insertText": "ConfigOverride",
      "filterText": "ConfigOverride",
      "sortText": "999999372",
      "detail": "com.fasterxml.jackson.databind.cfg.ConfigOverride",
      "kind": 7,
      "label": "ConfigOverride - com.fasterxml.jackson.databind.cfg"
    },
    {
      "data": {
        "uri": "file:///home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java",
        "rid": "9",
        "pid": "6",
        "decl_signature": "Lcom.github.victools.jsonschema.generator.ConfigFunction;"
      },
      "additionalTextEdits": [
        {
          "newText": "\nimport com.github.victools.jsonschema.generator.ConfigFunction;",
          "range": {
            "end": {
              "character": 47,
              "line": 7
            },
            "start": {
              "character": 47,
              "line": 7
            }
          }
        }
      ],
      "textEdit": {
        "newText": "ConfigFunction",
        "range": {
          "end": {
            "character": 12,
            "line": 1058
          },
          "start": {
            "character": 8,
            "line": 1058
          }
        }
      },
      "insertTextFormat": 2,
      "insertText": "ConfigFunction",
      "filterText": "ConfigFunction",
      "sortText": "999999372",
      "detail": "com.github.victools.jsonschema.generator.ConfigFunction",
      "kind": 8,
      "label": "ConfigFunction - com.github.victools.jsonschema.generator"
    },
    {
      "data": {
        "uri": "file:///home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java",
        "rid": "9",
        "pid": "7",
        "decl_signature": "Ljavax.naming.ConfigurationException;"
      },
      "additionalTextEdits": [
        {
          "newText": "\n\nimport javax.naming.ConfigurationException;",
          "range": {
            "end": {
              "character": 36,
              "line": 5
            },
            "start": {
              "character": 36,
              "line": 5
            }
          }
        }
      ],
      "textEdit": {
        "newText": "ConfigurationException",
        "range": {
          "end": {
            "character": 12,
            "line": 1058
          },
          "start": {
            "character": 8,
            "line": 1058
          }
        }
      },
      "insertTextFormat": 2,
      "insertText": "ConfigurationException",
      "filterText": "ConfigurationException",
      "sortText": "999999372",
      "detail": "javax.naming.ConfigurationException",
      "kind": 7,
      "label": "ConfigurationException - javax.naming"
    },
    {
      "data": {
        "uri": "file:///home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java",
        "rid": "9",
        "pid": "8",
        "decl_signature": "Ljavax.security.auth.callback.ConfirmationCallback;"
      },
      "additionalTextEdits": [
        {
          "newText": "\n\nimport javax.security.auth.callback.ConfirmationCallback;",
          "range": {
            "end": {
              "character": 36,
              "line": 5
            },
            "start": {
              "character": 36,
              "line": 5
            }
          }
        }
      ],
      "textEdit": {
        "newText": "ConfirmationCallback",
        "range": {
          "end": {
            "character": 12,
            "line": 1058
          },
          "start": {
            "character": 8,
            "line": 1058
          }
        }
      },
      "insertTextFormat": 2,
      "insertText": "ConfirmationCallback",
      "filterText": "ConfirmationCallback",
      "sortText": "999999372",
      "detail": "javax.security.auth.callback.ConfirmationCallback",
      "kind": 7,
      "label": "ConfirmationCallback - javax.security.auth.callback"
    },
    {
      "data": {
        "uri": "file:///home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java",
        "rid": "9",
        "pid": "9",
        "decl_signature": "Ljavax.security.auth.login.ConfigurationSpi;"
      },
      "additionalTextEdits": [
        {
          "newText": "\n\nimport javax.security.auth.login.ConfigurationSpi;",
          "range": {
            "end": {
              "character": 36,
              "line": 5
            },
            "start": {
              "character": 36,
              "line": 5
            }
          }
        }
      ],
      "textEdit": {
        "newText": "ConfigurationSpi",
        "range": {
          "end": {
            "character": 12,
            "line": 1058
          },
          "start": {
            "character": 8,
            "line": 1058
          }
        }
      },
      "insertTextFormat": 2,
      "insertText": "ConfigurationSpi",
      "filterText": "ConfigurationSpi",
      "sortText": "999999372",
      "detail": "javax.security.auth.login.ConfigurationSpi",
      "kind": 7,
      "label": "ConfigurationSpi - javax.security.auth.login"
    },
    {
      "data": {
        "uri": "file:///home/kyoncho/Sources/lsp/dap-mode/features/fixtures/test-project/src/main/java/temp/App.java",
        "rid": "9",
        "pid": "10",
        "decl_signature": "Ljavax.security.auth.login.Configuration;"
      },
      "additionalTextEdits": [
        {
          "newText": "\n\nimport javax.security.auth.login.Configuration;",
          "range": {
            "end": {
              "character": 36,
              "line": 5
            },
            "start": {
              "character": 36,
              "line": 5
            }
          }
        }
      ],
      "textEdit": {
        "newText": "Configuration",
        "range": {
          "end": {
            "character": 12,
            "line": 1058
          },
          "start": {
            "character": 8,
            "line": 1058
          }
        }
      },
      "insertTextFormat": 2,
      "insertText": "Configuration",
      "filterText": "Configuration",
      "sortText": "999999372",
      "detail": "javax.security.auth.login.Configuration",
      "kind": 7,
      "label": "Configuration - javax.security.auth.login"
    }
  ],
  "isIncomplete": null
}
```

**Comment by kiennq** [comment]
@yyoncho I think this is java language server problem.
The `configBuilder` candidate **doesn't** have `filterText` property, so it will use it's long label as matching candidate.
The built-in (and `lsp--fuzzy-score`) favors items that have higher matching ratio. So obviously longer the candidate, the lower matching ratio it will become.

Well you can try to tune `lsp--fuzzy-score-case-sensitiveness` to a higher value (it can even go pass 1) to force case sensitiveness to be more effective too.

**Comment by yyoncho** [comment]
> The `configBuilder` candidate **doesn't** have `filterText` property, so it will use it's long label as matching candidate.

IMO it this case the length of the candidate should not affect the score but only the match part. How hard will be to implement the vscode algorithm? 

I tried 1 and it still gives the same result.

**Comment by kiennq** [comment]
> IMO it this case the length of the candidate should not affect the score but only the match part. How hard will be to implement the vscode algorithm?
> 
> I tried 1 and it still gives the same result.

This was used so the shorter item should be on top.
You can set the `lsp--fuzzy-score-case-sensitiveness` to a larger value (for example 10, 30) and it will correctly prioritize the one which has same case.

I've taken a look at VsCode implementation, too much corner cases, heuristic and I don't really like it. It can be put on todo list though

**Comment by yyoncho** [comment]
> You can set the `lsp--fuzzy-score-case-sensitiveness` to a larger value (for example 10, 30) and it will correctly prioritize the one which has same case.

Why don't we have this as default? What is the negative side?

**Comment by kiennq** [comment]
> > You can set the `lsp--fuzzy-score-case-sensitiveness` to a larger value (for example 10, 30) and it will correctly prioritize the one which has same case.
> 
> Why don't we have this as default? What is the negative side?

The negative side is it may put items with matching case but the matches are far away from top + not consecutive matches in front.
Well, it's really preference then.

**Pull request merged**
