### PR TITLE
Changes command to be a function pointer

### PR DESCRIPTION
**Pull request by bkchr**
This patch changes the command to be a function pointer. In my setup, cargo, rls etc are not in global path, so I need to setup the path before lsp can find the programs. By making the command a function pointer, the function is called when the lsp-mode is activated and not when registered. This gives me the chance to setup the PATH properly.

For lsp-rust I added a pull request that reflects the required changes: https://github.com/emacs-lsp/lsp-rust/pull/7

If you would like to merge this, I could also adapt the other repos.

### CODE REVIEW

**Comment by vibhavp** [comment]
Thanks. However, this would probably break someone else's setup. Instead, you could add a new parameter `:command-fn` which returns the appropriate command to run.

**Comment by bkchr** [comment]
And how would I implement that for rust for example? 

You really think that finding rls when the client is created, would break other users setups?

**Comment by vibhavp** [comment]
> You really think that finding rls when the client is created, would break other users setups?

Perhaps. Some users might have their own defined clients, and changing the intended type of `:command` would break that. A way to implement this would be to add an optional `command-fn` param to both `lsp--make-*-connection` and `lsp-define-*-connection` variants and use that to obtain the command if it's non-nil.

**Comment by bkchr** [comment]
Okay, I added the command-fn as extra argument, as you proposed :)

**Comment by vibhavp** [comment]
Looks good, could you send the corresponding PR to `lsp-rust` too?

**Comment by bkchr** [comment]
I already opened the pull request for lsp-rust :) https://github.com/emacs-lsp/lsp-rust/pull/7

**Comment by bkchr** [comment]
@vibhavp will you merge these changes and the changes for lsp-rust? :)

**Comment by vibhavp** [comment]
Crap, forgot this one. Sorry!

**Pull request merged**
