### PR TITLE
chore: Remove downstream deps list

### PR DESCRIPTION
**Pull request by jcs090218**
Do we still need the list? I don't see it being used elsewhere. 🤔

### CODE REVIEW

**Comment by ericdallo** [comment]
@yyoncho has context about that

**Comment by yyoncho** [comment]
The idea of this section was to check if downstream deps can be compiled against lsp-mode.

**Comment by jcs090218** [comment]
The list is recorded here now:

https://github.com/emacs-lsp/lsp-mode/blob/f61671be7a1afc66603abb93e594d41cede825da/test/downstream/Eask#L22-L43

 It's better to maintain the list in the Eask file since the downstream list isn't part of the core. 🤔 WDYT?

**Comment by yyoncho** [comment]
> The list is recorded here now:
> 
> https://github.com/emacs-lsp/lsp-mode/blob/f61671be7a1afc66603abb93e594d41cede825da/test/downstream/Eask#L22-L43
> 
> It's better to maintain the list in the Eask file since the downstream list isn't part of the core. thinking WDYT?

As long as it works as expected.

**Comment by jcs090218** [comment]
FYI, I cannot merge this since it stops at the "Enable auto-merge (squash)".

**Review by ericdallo — APPROVED** [review]

**Pull request merged**
