### PR TITLE
Do not enable lsp-ui by default

### PR DESCRIPTION
**Pull request by yyoncho**
_Note_: this PR will be merged based on the up-votes and down-votes.

### CODE REVIEW

**Comment by seagle0128** [comment]
IMO, maybe lsp-ui can be enabled by default, but not all features should be enabled by default, e.g. `sideline`. I know many people don't like hover and diagnose sideline.

**Comment by kiennq** [comment]
I would second the option of @seagle0128, `lsp-ui` can be enabled by default, but not all of it features.
Personally, I only enable `lsp-ui-doc` and wire to display hover only when pressing `K` (`evil-lookup-func`).

Here is what I configured
``` elisp
(use-package lsp-ui
  :ensure t
  :diminish
  :hook (lsp-mode . lsp-ui-mode)
  :init
  (setq lsp-ui-peek-enable nil
        lsp-ui-sideline-enable nil
        lsp-ui-imenu-enable nil
        lsp-ui-doc-enable t
        lsp-ui-doc-position 'at-point
        lsp-ui-doc-include-signature t)
  (setq evil-lookup-func
        (lambda () (cond
                    ((and (not (display-graphic-p)) (boundp 'lsp-mode) lsp-mode)
                     (lsp-hover))
                    ((and (boundp 'lsp-ui-doc-mode) lsp-ui-doc-mode)
                     (lsp-ui-doc-show))
                    (t (woman)))))
  :config
  (lsp-ui-mode t)
  (advice-add #'lsp-ui-doc-hide
              :before-while
              (lambda (&rest _)
                  (or (overlayp lsp-ui-doc--inline-ov)
                      (let ((frame (lsp-ui-doc--get-frame)))
                        (and frame (frame-visible-p frame)))))
              '((name . --p)))
  (add-hook 'lsp-ui-doc-mode-hook
            (lambda ()
              (if lsp-ui-doc-mode
                  (progn
                    (add-hook 'post-command-hook #'lsp-ui-doc-hide nil t)
                    (remove-hook 'post-command-hook #'lsp-ui-doc--make-request t))
                (remove-hook 'post-command-hook 'lsp-ui-doc-hide t))))
  )
```

**Comment by dennismayr** [comment]
(I like `sideline` enabled :confused: )

**Comment by yyoncho** [comment]
> _Note_: this PR will be merged based on the up-votes and down-votes.

**Pull request closed without merging**
