### PR TITLE
chore: test diagnostic locations with a help of a mock LSP server

### PR DESCRIPTION
**Pull request by necto**
This implements the first part of #4501 
The mock server simulates detecting diagnostics and the tests document the behavior of `lsp-mode` upon receiving them.

### CODE REVIEW

**Comment by necto** [comment]
the `snapshot` Emacs version is broken regardless of this PR

**Comment by necto** [comment]
Only today I noticed that ubuntu-latest + 27.2 was failing after a recent commit. It is fixed now

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
Oops, I think I should have merged the other PR first. 🤔 Can you resolve the merge conflicts? Thanks!

**Comment by necto** [comment]
> Oops, I think I should have merged the other PR first. 🤔 Can you resolve the merge conflicts? Thanks!

No, problem. #4503,  that you merged, supersedes this one. I broke them into two steps to reduce the amount of code to review.

**Pull request closed without merging**
