### PR TITLE
Consider hover contents consisting of a single line as signatures

### PR DESCRIPTION
**Pull request by CyberShadow**
```
When textDocument/hover returns a single string consisting of a single
line, show it in the minibuffer regardless of lsp-eldoc-render-all.
```

### CODE REVIEW

**Comment by yyoncho** [comment]
Can you share which language servers you have used for testing?

**Comment by CyberShadow** [comment]
I'm writing my own LSP server, though I think the change makes sense regardless of language. Perhaps the logic could be mode more general if that's something worth discussing.

**Comment by CyberShadow** [comment]
If you have reservations about this change, I'm fine with addressing this locally (i.e. setting `lsp-eldoc-render-all`).

**Comment by yyoncho** [comment]
I will have to test it with some of the popular language servers to see how it works.

Related: https://github.com/microsoft/language-server-protocol/issues/772

**Comment by yyoncho** [comment]
Merging as it is and if someone complains(e. g. if there is huge single line text) we will consider make it configurable. 

Thank you.

**Comment by jsravn** [comment]
@yyoncho what would you think about displaying the first line if MarkupContent is returned? As-is most language servers are returning MarkupContent in my experience - so eldoc is never rendered. There isn't a great solution since onHover is also used for documentation popups.

**Comment by yyoncho** [comment]
@jsravn either this or take N chars. I am fine with this change.

**Comment by jsravn** [comment]
@yyoncho https://github.com/emacs-lsp/lsp-mode/pull/1607

**Pull request merged**
