### PR TITLE
Add lsp-grammarly page

### PR DESCRIPTION
**Pull request by jcs090218**

### CODE REVIEW

**Review by yyoncho — APPROVED** [review]

**Review by ericdallo — APPROVED** [review]
Would you mind add to CHANGELOG as well?

**Comment by jcs090218** [comment]
Done! :)

**Comment by yyoncho** [comment]
You may add your package to lsp-client-packages

**Review by ericdallo — APPROVED** [review]

**Comment by jcs090218** [comment]
> You may add your package to lsp-client-packages

Added! Thanks! 👍

**Pull request merged**
