### PR TITLE
Fix handling of overlapping edits

### PR DESCRIPTION
**Pull request by yyoncho**
* see https://github.com/Microsoft/language-server-protocol/commit/005d12dc021b9ea087e4d1fe4915c43fe7860be8

### CODE REVIEW

**Comment by yyoncho** [comment]
Fixes point 3 from https://github.com/emacs-lsp/lsp-mode/issues/309

**Comment by vibhavp** [comment]
Not sure how reversing the text edit order would conform to the standard. Quoting from the spec:

> If multiple inserts have the same position, the order in the array defines which edit to apply first.

By reversing the edits array, `TextEdit`s that need to be applied later would be applied _first_.

**Comment by yyoncho** [comment]
@vibhavp 

You are right, the operations must be applied in the same order they are received. 

Assuming lsp-mode has received the following updates

> [0, 0, "Hello"]
> [0, 0, " world!"] 
> [1, 0, "Second line..."]

Before the fix after  the updates are sorted they will be applied in the following order:
3, 1, 2, after the fix they will be applied in the correct order 3, 2, 1.

Here it is the same code in vscode. 
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeTextBuffer.ts#L207
It is applying stable sort which reverses the elements in the map reversing the original order before applying the edits. In the emacs use case the sort function is already performing stable sort so we need to ensure that the overlapping edits are reversed before applying. 

I have performed few debug session of the vscode and if you are still not convinced I might attach few screenshots of the edits when they are received and before they are applied.

**Comment by vibhavp** [comment]
Ah, I completely forgot about why we sorted text edits in the first place. I'll add some additional documentation to this, thanks.

**Pull request merged**
