### PR TITLE
Fix ada language server download path

### PR DESCRIPTION
**Pull request by ivvil**
Tested for linux x64

### CODE REVIEW

**Comment by ivvil** [comment]
Seems like it's downloading it as a *.tar instead of a *.tar.gz

**Comment by jcs090218** [comment]
I'm not sure about this. Does this work on Windows? 🤔

**Comment by jcs090218** [comment]
Why did you close this? I would like this to be merged. 🤔

**Comment by ivvil** [comment]
Seems like what I was trying to fix got merged on #4567

**Pull request closed without merging**
