### PR TITLE
render first line if not all

### PR DESCRIPTION
**Pull request by scturtle**
Specifically to make rust-analyzer more usable.

### CODE REVIEW

**Comment by yyoncho** [comment]
Can you comment whether reverting the change(c1df55e) I reverted due to unknown lsp-ui issue works fine with rust analyzer? I am a bit concerned our PR is too custom and it will potentially break due to minor mismatches(see below).  If revering c1df55e is not fine for you, I would prefer to create an extension point (e. g. lsp-render-function) which will be used to customize the hover rendering. This part of the code has been changing like from the start of the project due to the fact that onHover info is not designed to work with eldoc. 

I tested it with a couple of servers and it does not work fine with at least one server. 

```
<<<< ruby-ls:8927
{
  "jsonrpc": "2.0",
  "id": 110,
  "result": {
    "contents": {
      "kind": "markdown",
      "value": "[#ordinal](solargraph:/document?query=%23ordinal)\n\n(a, b, c)"
    }
  }
}
```

**Comment by scturtle** [comment]
I think reverting c1df55e is the same as turning on `lsp-eldoc-render-all` which is too much for most of the time. I will try the custom function way (with my little elisp knowledge). Is another option like `lsp-eldoc-render-first-line` acceptable to provide the proposed heuristic?

**Comment by yyoncho** [comment]
> Is another option like lsp-eldoc-render-first-line acceptable to provide the proposed heuristic?

I guess it is fine, as long as we make the extract logic a bit more robust and fallback to the full text when the input format does not match our expectations.

(I will use ' instead of \`)

I think that if the logic is to extract the first code block(the content between ''' and ''') and then use render markdown function will work in more cases. E. g.

> '''
> without language
> '''

> ''' single line '''

**Comment by scturtle** [comment]
Not quite useful.

**Pull request closed without merging**
