### PR TITLE
Move clients to folder

### PR DESCRIPTION
**Pull request by ericdallo**
After [this](https://github.com/melpa/melpa/pull/7084) we can now reorganize the clients structure.

### CODE REVIEW

**Comment by ericdallo** [comment]
@kiennq I'm kind of stuck on those tests, I already changed to load the clients folder but for some reason CI doesn't find it

**Comment by leungbk** [comment]
> @kiennq I'm kind of stuck on those tests, I already changed to load the clients folder but for some reason CI doesn't find it

I tried running CI on my fork just now with your branch. Everything passes when you `(require 'lsp-pyls)` in `lsp-integration-test.el`

**Comment by kiennq** [comment]
> I tried running CI on my fork just now with your branch. Everything passes when you `(require 'lsp-pyls)` in `lsp-integration-test.el`

Is there a real break on that. I mean `lsp-pyls` should be required with `lsp-client-packages` already.
Else we will have some user breaking change

**Comment by yyoncho** [comment]
> Is there a real break on that. I mean `lsp-pyls` should be required with `lsp-client-packages` already.
> Else we will have some user breaking change

We will see when melpa kicks in. But generally the fix is odd, because M-x lsp will also do require lsp-pyls.

**Comment by ericdallo** [comment]
Thanks for the help @leungbk

**Comment by iitalics** [comment]
This seems like it breaks lsp-mode for me. None of the clients can be found, so i get errors like `File mode specification error: (file-missing Cannot open load file No such file or directory lsp-rust)`.

**Comment by ericdallo** [comment]
@iitalics  make sure you have byte-compiled all lsp files, for doom-emacs you probably need to `rm -rf ~/.emacs.d/.local/straight/build/lsp-mode`

**Comment by iitalics** [comment]
This is a fresh lsp-mode install through straight + use-package on otherwise vanilla emacs. Am I supposed to run additional commands to compile stuff?

**Comment by ericdallo** [comment]
if you are using straight recipe manually, make sure the `clients` folder are included on your recipe, check here for the recipe: https://github.com/melpa/melpa/blob/master/recipes/lsp-mode#L1-L4

**Comment by iitalics** [comment]
I see, I will do that.  Is there any way to get this simple invocation to work in the future?
```
(use-package lsp-mode)
```
Or at least could you document more clearly how to setup lsp-mode through use-package?

**Comment by iitalics** [comment]
This has worked in the past and it is odd to see it suddenly break on a new install.

**Comment by ericdallo** [comment]
We have [this documentation](https://emacs-lsp.github.io/lsp-mode/page/installation/) and [this PR waiting to be merged](https://github.com/emacs-lsp/lsp-mode/pull/2003)

**Comment by iitalics** [comment]
Ah, thanks.

**Comment by kiennq** [comment]
Unless you specify the recipe yourselves when using `straight.el` or you have a stale MELPA recipe repository, `straight.el` should also pull recipe from MELPA.
https://github.com/raxod502/straight.el/blob/master/straight.el#L2662
@raxod502 for more advices.

**Comment by raxod502** [comment]
Yes. I will not claim that `straight.el` has perfect MELPA compatibility, but MELPA compatibility is far from the most likely explanation for issues like this. As @kiennq says, you should make sure you have pulled the latest version of MELPA so that you have the updated recipe.

**Pull request merged**
