### PR TITLE
lsp-completion--exit-fn: works with non props candidate

### PR DESCRIPTION
**Pull request by kiennq**
In case of just using default `completion-at-point` (in that case `completion-in-region-function` will be `completion--in-region`), the `:exit-function` will be called with selected item as string without any properties that we built up during filtering phase.
We need a way to re-associated the striped string with the full one.

The propose here is:
- Remember the last completion results in `lsp-completion--last-result`, use that to trace back to full string in `:exit-function`.
- Make `try-completion` will always return `nil` (no exact completion item) so that the selection will always shown and prevent early clean up of completion cache.

This will also server as first step for #1894

### CODE REVIEW

**Comment by yyoncho** [comment]
> will be called with selected item as string without any properties that we built up during filtering phase.

Isn't that emacs bug?

**Comment by kiennq** [comment]
> > will be called with selected item as string without any properties that we built up during filtering phase.
> 
> Isn't that emacs bug?

Is it? I think there's no guarantee that the string's properties will be preserved when passed to `:exit-function`.

For that's by design since the completion items will be displayed in other buffer in case of default `completion-in-region-function`.
image

Thus it will mostly cannot retain the property when selecting one of them.

Even if this's a bug (not likely), we still need to work-around in `lsp-mode` since it will not be fixed in pre Emacs 28.

**Comment by yyoncho** [comment]
Hm, some of the previous capf implementations used to preserve the properties.

**Comment by yyoncho** [comment]
The text properties used to work. I even filed a helm issue - https://github.com/emacs-helm/helm/issues/2265#issuecomment-576582659 . Do you know what broke them?

**Comment by kiennq** [comment]
AFAIK, `ivy`, `company`, `emacs-helm` are preserving text properties for `:exit-function`.

However, the default function for `completion-in-region-function` (which is `completion--in-region`) doesn't do that.
I've checked Emacs25 and it seems that behavior is there too, so it's pretty much default behavior.
https://github.com/emacs-mirror/emacs/blob/c3ff6712ad24fcf45874dc0665a8606e9b2208a4/lisp/minibuffer.el#L1005

I think you can test this by disable `helm-mode` and manually trigger `completion-at-point` (bind to `C-M-i`), then select item with mouse

**Review by yyoncho — APPROVED** [review]

**Pull request merged**
