### PR TITLE
Fix CI and check with Emacs minimum requirement

### PR DESCRIPTION
**Pull request by jcs090218**

### CODE REVIEW

**Comment by jcs090218** [comment]
@ericdallo The PR labeler kept removing the CI label. Is there a way so it doesn't do this? 😕

**Comment by ericdallo** [comment]
Oh, really odd, it seems you manually added it so the bot it's removing :facepalm: 
I don't know how to fix that for this pr :/

**Comment by ericdallo** [comment]
We could open an issue on the pr labeler GH Action

**Comment by jcs090218** [comment]
It’s okay. This isn’t a big deal for now. Can anyone review this PR? This should be ready to go! :)

**Review by yyoncho — APPROVED** [review]
Thank you!

**Pull request merged**
