### PR TITLE
Add support for installing Ada Language Server.

### PR DESCRIPTION
**Pull request by brownts**

### CODE REVIEW

**Review by jcs090218 — APPROVED** [review]

**Comment by brownts** [comment]
Was there a reason this wasn't merged, or just an oversight?

**Comment by brownts** [comment]
@yyoncho @jcs090218 

Ping

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
Can you resolve conflicts?

**Comment by brownts** [comment]
> Can you resolve conflicts?

Conflicts are now resolved.

**Comment by brownts** [comment]
Ping

**Pull request merged**
