### PR TITLE
Add mint-lang client

### PR DESCRIPTION
**Pull request by zw963**
Add elementary mint support. #3678

### CODE REVIEW

**Comment by yyoncho** [comment]
Can you add an entry in clients.json?

**Comment by jcs090218** [comment]
Maybe update the CHANGELOG as well?

**Comment by zw963** [comment]
Done, please check.

There is one more issue, i have to  `(require 'lsp-mint)` manually in my own to make those config take effect, but, it seem like some others client will load automatically when `lsp` is running in mode hook, right?

**Comment by yyoncho** [comment]
You have to update lsp-client-packages just like the sample PR I linked.

**Comment by zw963** [comment]
done, please have a look, thank you.

**Review by yyoncho — APPROVED** [review]

**Pull request merged**
