### PR TITLE
Check return value before access hashtable

### PR DESCRIPTION
**Pull request by conao3**
Hi!
Thanks for such a great package!

I found `lsp--parser-on-message` occuor error in some condition.

This error occurs when I using `lsp-mode` with `clangd` for cpp
files.

Here is the backtrace. So, I fix code to check return value
before access hashtable via `gethash`.
```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)                             
  gethash("range" nil)                                                                           
  (let* ((hover input0) (range\? (gethash "range" hover)) (contents (gethash "contents" hover))) 
  (closure (cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspace-tag
  apply((closure (cl-struct-lsp--log-entry-tags cl-struct-lsp-session-tags cl-struct-lsp--workspa
  (save-current-buffer (set-buffer buf) (apply callback args))                                   
  (closure ((cleanup-hooks closure ((buf . #<buffer main.cpp>) (hooks (kill-buffer-hook . t) (aft
  funcall((closure ((cleanup-hooks closure ((buf . #<buffer main.cpp>) (hooks (kill-buffer-hook .
  (progn (funcall callback (if no-merge results (lsp--merge-results (-map (function cl-rest) resu
  (if (and (not (eq (length errors) (length workspaces))) (eq (+ (length errors) (length results)
  (closure ((errors) (results (#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equa
  funcall((closure ((errors) (results (#s(lsp--workspace :ewoc nil :server-capabilities #<hash-ta
  (closure ((callback closure ((errors) (results (#s(lsp--workspace :ewoc nil :server-capabilitie
  funcall((closure ((callback closure ((errors) (results (#s(lsp--workspace :ewoc nil :server-cap
  (progn (funcall callback (lsp:json-response-result json-data)) (remhash id (progn (or (and (mem
  (if callback (progn (funcall callback (lsp:json-response-result json-data)) (remhash id (progn 
  (let* ((--dash-source-146-- (gethash id (progn (or (and (memq ... cl-struct-lsp--client-tags) t
  (cond ((eq val (quote response)) (progn (or id (cl--assertion-failed (quote id))) nil) (let* ((
  (let* ((val (lsp--get-message-type json-data))) (cond ((eq val (quote response)) (progn (or id 
  (let* ((client (progn (or (and (memq (type-of workspace) cl-struct-lsp--workspace-tags) t) (sig
  (let ((lsp--cur-workspace workspace)) (let* ((client (progn (or (and (memq ... cl-struct-lsp--w
  (condition-case err (let ((lsp--cur-workspace workspace)) (let* ((client (progn (or (and ... t)
  lsp--parser-on-message(#<hash-table equal 3/65 0x26751f9> #s(lsp--workspace :ewoc nil :server-c
  #f(compiled-function (proc input) #<bytecode
  0x2d82911>)(#<process clangd<1>> "Content-Length:
 ```

### CODE REVIEW

**Comment by yyoncho** [comment]
Isn't that fixed by https://github.com/emacs-lsp/lsp-mode/commit/890db8cf0b208fd855c9490f80154ffd606a6637 ?

**Comment by conao3** [comment]
Yes! There're no issues after update!
Thanks.

**Comment by conao3** [comment]
Don't you need this commit?
It is true that we don't get any errors, but it doesn't check the return value.
I think merging this code would increase the robustness.

**Comment by yyoncho** [comment]
> I think merging this code would increase the robustness.

I am not quite sure which particular condition we are handling with this change, can you elaborate?

**Comment by conao3** [comment]
If `lsp--client-response-handlers` returns `nil`, then No error.
`lsp--client-response-handlers` will never return `nil`. If this assumption holds, then the commit is not necessary.

**Comment by yyoncho** [comment]
lsp--client-response-handlers cannot return nil. Getting the value from it might return nil but I prefer having an error in this case because it will be an indication that something is wrong.

**Comment by conao3** [comment]
OK, agree. thanks.

**Pull request closed without merging**
