### PR TITLE
perl: add new client for PLS server

### PR DESCRIPTION
**Pull request by c-alpha**
Ref: https://github.com/FractalBoy/perl-language-server

Also updating the priority order, so that the new client pls is preferred over perl-languag-server, since the PLS server supports auto-completion, whereas Perl::LanguageServer does not.

### CODE REVIEW

**Comment by jcs090218** [comment]
Might update the CHANGELOG as well?

**Comment by c-alpha** [comment]
> Might update the CHANGELOG as well?

Ah, overlooked that. Thanks for the gentle prod; will do!

**Comment by c-alpha** [comment]
> > Might update the CHANGELOG as well?
> 
> Ah, overlooked that. Thanks for the gentle prod; will do!

Done.

**Comment by c-alpha** [comment]
The error in `CI / unix-test` appears to be some failing package install:
```
[...]
Package ‘lsp-pyright’ installed.
Contacting host: melpa.org:443
Debugger entered--Lisp error: (error "Cannot resolve lock conflict in batch mode")
  signal(error ("Cannot resolve lock conflict in batch mode"))
```

Will the test be re-run automatically?

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
Thank you!

**Comment by c-alpha** [comment]
Ivan Yonchovski ***@***.***> writes:

> Thank you!

Thank you, too!

**Pull request merged**
