### PR TITLE
Fix rust servers custom docs

### LINKED ISSUE #2848: Tidy up lsp-rust.md documentation
Checked the rust doc page 
https://emacs-lsp.github.io/lsp-mode/page/lsp-rust/
after my PR got merged 
#2776 

Three things stood out:

1. The gifs that I added aren't rendered 
https://github.com/emacs-lsp/lsp-mode/pull/2776/files?file-filters%5B%5D=.gif

I placed my gifs in docs/manual-language-docs, while all other media lives in top-level examples/

2. The server section still defaults to RLS
https://emacs-lsp.github.io/lsp-mode/page/lsp-rust/#server

Though rust-analyzer has yet to become the official LSP server for rust, it's already widely used and is the recommended server. lsp-mode documentation should reflect that and be consistent with the default config. 

3. The RLS section is above rust-analyzer
https://emacs-lsp.github.io/lsp-mode/page/lsp-rust/#rls

Same as above it's worth placing the now default rust-analyzer above rls in the docs.

### PR DESCRIPTION
**Pull request by petr-tik**
Following the example of different PHP servers, create
separate pages for rust-analyzer and rust-rls

move the gifs to the examples dir with other media

Close #2848

### CODE REVIEW

**Comment by petr-tik** [comment]
I think this might be missing all the `lsp-rust-*` variables that aren't `lsp-rust-analyzer-*`. 

Can you please confirm if they apply to both and if so whether I should special-case this in the doc generator code?

**Review by yyoncho — APPROVED** [review]

**Review by ericdallo — CHANGES_REQUESTED** [review]
@petr-tik,  to separate both rust implementation pages into 2 docs, you need to change `mkdocs.yml` as well renaming the current one to `Rust (rust-analyzer)` and creating a new one for `Rust (rls)`

**Comment by petr-tik** [comment]
> @petr-tik, to separate both rust implementation pages into 2 docs, you need to change `mkdocs.yml` as well renaming the current one to `Rust (rust-analyzer)` and creating a new one for `Rust (rls)`

Awesome. Am addressing now, what about my previous question:

> I think this might be missing all the `lsp-rust-*` variables that aren't `lsp-rust-analyzer-*`.
> 
> Can you please confirm if they apply to both and if so whether I should special-case this in the doc generator code?

**Comment by ericdallo** [comment]
> I think this might be missing all the lsp-rust-* variables that aren't lsp-rust-analyzer-*.
> Can you please confirm if they apply to both and if so whether I should special-case this in the doc generator code?

You need to rename the `:group` for each variable in lsp-rust.el following the `name` of the `lsp-clients.json`, for example, for rls you need to rename the variables to use a `'lsp-rust-rls` as the `:group`.

I recommend you test the changes locally running `make local-webapge` on lsp-mode root, it should generate and start the page at localhost:8000

**Comment by petr-tik** [comment]
> I recommend you test the changes locally running `make local-webapge` on lsp-mode root, it should generate and start the page at localhost:8000

I get this when i run the command you suggested

```bash
Unable to find image 'docker.pkg.github.com/emacs-lsp/docs-image/docs-image:latest' locally
docker: Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.

# logging in on its own works
docker login docker.pkg.github.com
Authenticating with existing credentials...
Login Succeeded
```

**Comment by petr-tik** [comment]
some custom variables are shared by rust-analyzer and rust-rls. Should I leave them in the lsp-rust group and move rls-specific variables to `lsp-rust-rls`?

**Comment by ericdallo** [comment]
Did you login to docker GitHub like said on the error log? Not sure I need to give some permission o GitHub to allow anyone download the docker image.

> some custom variables are shared by rust-analyzer and rust-rls. Should I leave them in the lsp-rust group and move rls-specific variables to lsp-rust-rls?

LGTM

**Comment by yyoncho** [comment]
@ericdallo anything else here?

**Comment by ericdallo** [comment]
@yyoncho LGTM, I think we can merge it and check if those 5 vars are present

**Comment by yyoncho** [comment]
Thank you @petr-tik!

**Pull request merged**
