### PR TITLE
lsp-terraform: fix invalid keys

### PR DESCRIPTION
**Pull request by daedric**
Hi,
I'm a doomemacs user and I got errors in the terraform client. I'm not sure when/where those changes occurred.
Let me know whether this needs rework,
Cheers,

### CODE REVIEW

**Comment by yyoncho** [comment]
CI does not like this change. Note that when lsp-interface member is using _ it is converted in - when destructoring.

cc @psibi

**Comment by psibi** [comment]
@daedric Can you let me know the exact error message you are seeing ? Also, I remember someone previously facing same issue which got resolved by cleaning up the old `*.elc` and `*.eln` files.

**Comment by daedric** [comment]
it started to work again without :/
Sorry for the noise

**Comment by psibi** [comment]
@daedric No worries, thanks for the confirmation! I remember same thing happening previously to someone too: https://github.com/emacs-lsp/lsp-mode/pull/3757

**Comment by jmcarcell** [comment]
I also get the same error when using lsp from master but not with 8.0.0

**Comment by daedric** [comment]
Actually it is strange, for me:
- if I open a Go file with master, I'll get the error every time and need the patch;
- if I open a C++ file with master, it will work and the LSP starts.

I worked it around by opening a Go file before a C++ because it makes it work. I did not have the time to investigate properly yet.

**Comment by yyoncho** [comment]
clean installation should fix the issue.

**Comment by jmcarcell** [comment]
@yyoncho it doesn't do it for me fater deleting everything `lsp*` in my packages folder and also the built folders. I actually have no idea because I have two computers both with the same version of emacs from Arch Linux that share a configuration and for one of them this issue happens consistently and for the other it doesn't

**Pull request closed without merging**
