### PR TITLE
Add support for R language server

### PR DESCRIPTION
**Pull request by sei40kr**
Add support for R language server.

See this:
https://github.com/REditorSupport/languageserver

### CODE REVIEW

**Comment by yyoncho** [comment]
Looks good, can you update also the [Supported languages](https://github.com/emacs-lsp/lsp-mode#supported-languages) section in the readme?

**Comment by sei40kr** [comment]
@yyoncho 
Thanks for kindly review. I've updated it.

**Comment by yyoncho** [comment]
Thank you and congrats for your first `lsp-mode` PR! :tada:

**Comment by Emiller88** [comment]
@sei40kr The link to the installation command points to https://github.com/andrew-christianson/lsp-python-ms/ and not to the installation portion of the README on languageserver.

**Pull request merged**
