### PR TITLE
Add client for Ruby's TypeProf

### PR DESCRIPTION
**Pull request by buzztaiki**
Add `lsp-typeprof` using https://github.com/ruby/typeprof.

### CODE REVIEW

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
Can you resolve the conflicts?

**Comment by buzztaiki** [comment]
> Can you resolve the conflicts?

resolved.

**Comment by buzztaiki** [comment]
Ah, should I use rebase instead of merge?

**Comment by yyoncho** [comment]
Thank you for contributing to `lsp-mode`!

> Ah, should I use rebase instead of merge?

We use merge squash so it doesn't matter.

**Pull request merged**
