### PR TITLE
Filter lenses that are not visible without converting to Position

### PR DESCRIPTION
**Pull request by yyoncho**

### CODE REVIEW

**Comment by lassemaatta** [comment]
@yyoncho FYI: I'm getting some errors with the latest `lsp-mode` regarding lenses, which might have something to do with this commit. 

<details>
<pre>Debugger entered--Lisp error: (wrong-type-argument hash-table-p (:line 86 :character 0))
  lsp--position-compare((:line 86 :character 0) #<hash-table equal 2/2 0x1579e557991d>)
  lsp-point-in-range?(#<hash-table equal 2/2 0x1579e557991d> #<hash-table equal 2/65 0x1579e106a501>)
  lsp--lens-backend-not-loaded?(#<hash-table equal 2/65 0x1579e106a501> #<hash-table equal 3/3 0x1579e5579899>)
  apply(lsp--lens-backend-not-loaded? (#<hash-table equal 2/65 0x1579e106a501> #<hash-table equal 3/3 0x1579e5579899>))
  #f(compiled-function (&rest args2) #<bytecode 0x6c3a3a383e46487>)(#<hash-table equal 3/3 0x1579e5579899>)
  #f(compiled-function (elt) #<bytecode 0x5a52f620ef625cc>)(#<hash-table equal 3/3 0x1579e5579899>)
  mapcar(#f(compiled-function (elt) #<bytecode 0x5a52f620ef625cc>) (#<hash-table equal 3/3 0x1579e5579899> #<hash-table equal 3/3 0x1579e557998d> #<hash-table equal 3/3 0x1579e5579a6d> #<hash-table equal 3/3 0x1579e5579b4d> #<hash-table equal 3/3 0x1579e5579c2d> #<hash-table equal 3/3 0x1579e5579d21> #<hash-table equal 3/3 0x1579e5579e01> #<hash-table equal 3/3 0x1579e5579ee1> #<hash-table equal 3/3 0x1579e5579fc1> #<hash-table equal 3/3 0x1579e557a0a1>))
  #f(compiled-function #'sequence #<bytecode 0x184095881e723fb4>)(#f(compiled-function (elt) #<bytecode 0x5a52f620ef625cc>) (#<hash-table equal 3/3 0x1579e5579899> #<hash-table equal 3/3 0x1579e557998d> #<hash-table equal 3/3 0x1579e5579a6d> #<hash-table equal 3/3 0x1579e5579b4d> #<hash-table equal 3/3 0x1579e5579c2d> #<hash-table equal 3/3 0x1579e5579d21> #<hash-table equal 3/3 0x1579e5579e01> #<hash-table equal 3/3 0x1579e5579ee1> #<hash-table equal 3/3 0x1579e5579fc1> #<hash-table equal 3/3 0x1579e557a0a1>))
  apply(#f(compiled-function #'sequence #<bytecode 0x184095881e723fb4>) #f(compiled-function (elt) #<bytecode 0x5a52f620ef625cc>) (#<hash-table equal 3/3 0x1579e5579899> #<hash-table equal 3/3 0x1579e557998d> #<hash-table equal 3/3 0x1579e5579a6d> #<hash-table equal 3/3 0x1579e5579b4d> #<hash-table equal 3/3 0x1579e5579c2d> #<hash-table equal 3/3 0x1579e5579d21> #<hash-table equal 3/3 0x1579e5579e01> #<hash-table equal 3/3 0x1579e5579ee1> #<hash-table equal 3/3 0x1579e5579fc1> #<hash-table equal 3/3 0x1579e557a0a1>) nil)
  seq-map(#f(compiled-function (elt) #<bytecode 0x5a52f620ef625cc>) (#<hash-table equal 3/3 0x1579e5579899> #<hash-table equal 3/3 0x1579e557998d> #<hash-table equal 3/3 0x1579e5579a6d> #<hash-table equal 3/3 0x1579e5579b4d> #<hash-table equal 3/3 0x1579e5579c2d> #<hash-table equal 3/3 0x1579e5579d21> #<hash-table equal 3/3 0x1579e5579e01> #<hash-table equal 3/3 0x1579e5579ee1> #<hash-table equal 3/3 0x1579e5579fc1> #<hash-table equal 3/3 0x1579e557a0a1>))
  seq-filter(#f(compiled-function (&rest args2) #<bytecode 0x6c3a3a383e46487>) (#<hash-table equal 3/3 0x1579e5579899> #<hash-table equal 3/3 0x1579e557998d> #<hash-table equal 3/3 0x1579e5579a6d> #<hash-table equal 3/3 0x1579e5579b4d> #<hash-table equal 3/3 0x1579e5579c2d> #<hash-table equal 3/3 0x1579e5579d21> #<hash-table equal 3/3 0x1579e5579e01> #<hash-table equal 3/3 0x1579e5579ee1> #<hash-table equal 3/3 0x1579e5579fc1> #<hash-table equal 3/3 0x1579e557a0a1>))
  lsp-lens--backend-fetch-missing((#<hash-table equal 3/3 0x1579e5579899> #<hash-table equal 3/3 0x1579e557998d> #<hash-table equal 3/3 0x1579e5579a6d> #<hash-table equal 3/3 0x1579e5579b4d> #<hash-table equal 3/3 0x1579e5579c2d> #<hash-table equal 3/3 0x1579e5579d21> #<hash-table equal 3/3 0x1579e5579e01> #<hash-table equal 3/3 0x1579e5579ee1> #<hash-table equal 3/3 0x1579e5579fc1> #<hash-table equal 3/3 0x1579e557a0a1>) #f(compiled-function (lenses version) #<bytecode -0xc35f4c7b05414d5>) 767)
  #f(compiled-function (lenses) #<bytecode -0x188cbdd763339455>)(((#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 22/22 0x1579e4b17db1> :registered-server-capabilities (#s(lsp--registered-capability :id "id" :method "workspace/didChangeWatchedFiles" :options #<hash-table equal 1/1 0x1579e4a5ca9d>)) :root "/home/lassemaatta/work/vaahtera" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn workspace) #<bytecode 0x13767afd27dfe91d>) :test? lsp-clojure--build-command) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 1/65 0x1579e34c50c3> :request-handlers #<hash-table equal 0/65 0x1579e3692797> :response-handlers #<hash-table eql 0/65 0x1579e336f6ed> :prefix-function nil :uri-handlers #<hash-table equal 1/65 0x1579e4742535> :action-handlers #<hash-table equal 1/65 0x1579e33b6191> :major-modes (clojure-mode clojurec-mode clojurescript-mode clojure-ts-mode) :activation-fn nil :priority 0 :server-id clojure-lsp :multi-root nil :initialization-options (:dependency-scheme "jar" :show-docs-arity-on-same-line? t) :semantic-tokens-faces-overrides (:types (("macro" . font-lock-keyword-face) ("keyword" . clojure-keyword-face) ("event" . default))) :custom-capabilities ((experimental (testTree . t))) :library-folders-fn #f(compiled-function (workspace) #<bytecode -0x47e1d70f7d62878>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x1579e1e75427> :download-server-fn #f(compiled-function (client callback error-callback update?) #<bytecode -0x15a151ffef4f9f07>) :download-in-progress? nil :buffers nil :synchronize-sections nil) :host-root nil :proc #<process clojure-lsp> :cmd-proc #<process clojure-lsp> :buffers (#<buffer core.clj> #<buffer app_form_util.clj> #<buffer set_work_i_test.clj> #<buffer fixture.clj> #<buffer api_test.clj> #<buffer app_work_util.clj>) :semantic-tokens-faces nil :semantic-tokens-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x1579e1759b8f> :watches #<hash-table equal 0/65 0x1579e1759baf> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 118/145 0x1579e187cc8d> :work-done-tokens #<hash-table equal 0/65 0x1579e187ccad>) . [#<hash-table equal 3/3 0x1579e5579899> #<hash-table equal 3/3 0x1579e557998d> #<hash-table equal 3/3 0x1579e5579a6d> #<hash-table equal 3/3 0x1579e5579b4d> #<hash-table equal 3/3 0x1579e5579c2d> #<hash-table equal 3/3 0x1579e5579d21> #<hash-table equal 3/3 0x1579e5579e01> #<hash-table equal 3/3 0x1579e5579ee1> #<hash-table equal 3/3 0x1579e5579fc1> #<hash-table equal 3/3 0x1579e557a0a1>])))
  apply(#f(compiled-function (lenses) #<bytecode -0x188cbdd763339455>) ((#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 22/22 0x1579e4b17db1> :registered-server-capabilities (#s(lsp--registered-capability :id "id" :method "workspace/didChangeWatchedFiles" :options #<hash-table equal 1/1 0x1579e4a5ca9d>)) :root "/home/lassemaatta/work/vaahtera" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn workspace) #<bytecode 0x13767afd27dfe91d>) :test? lsp-clojure--build-command) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 1/65 0x1579e34c50c3> :request-handlers #<hash-table equal 0/65 0x1579e3692797> :response-handlers #<hash-table eql 0/65 0x1579e336f6ed> :prefix-function nil :uri-handlers #<hash-table equal 1/65 0x1579e4742535> :action-handlers #<hash-table equal 1/65 0x1579e33b6191> :major-modes (clojure-mode clojurec-mode clojurescript-mode clojure-ts-mode) :activation-fn nil :priority 0 :server-id clojure-lsp :multi-root nil :initialization-options (:dependency-scheme "jar" :show-docs-arity-on-same-line? t) :semantic-tokens-faces-overrides (:types (("macro" . font-lock-keyword-face) ("keyword" . clojure-keyword-face) ("event" . default))) :custom-capabilities ((experimental (testTree . t))) :library-folders-fn #f(compiled-function (workspace) #<bytecode -0x47e1d70f7d62878>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x1579e1e75427> :download-server-fn #f(compiled-function (client callback error-callback update?) #<bytecode -0x15a151ffef4f9f07>) :download-in-progress? nil :buffers nil :synchronize-sections nil) :host-root nil :proc #<process clojure-lsp> :cmd-proc #<process clojure-lsp> :buffers (#<buffer core.clj> #<buffer app_form_util.clj> #<buffer set_work_i_test.clj> #<buffer fixture.clj> #<buffer api_test.clj> #<buffer app_work_util.clj>) :semantic-tokens-faces nil :semantic-tokens-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x1579e1759b8f> :watches #<hash-table equal 0/65 0x1579e1759baf> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 118/145 0x1579e187cc8d> :work-done-tokens #<hash-table equal 0/65 0x1579e187ccad>) . [#<hash-table equal 3/3 0x1579e5579899> #<hash-table equal 3/3 0x1579e557998d> #<hash-table equal 3/3 0x1579e5579a6d> #<hash-table equal 3/3 0x1579e5579b4d> #<hash-table equal 3/3 0x1579e5579c2d> #<hash-table equal 3/3 0x1579e5579d21> #<hash-table equal 3/3 0x1579e5579e01> #<hash-table equal 3/3 0x1579e5579ee1> #<hash-table equal 3/3 0x1579e5579fc1> #<hash-table equal 3/3 0x1579e557a0a1>])))
  #f(compiled-function (&rest args) #<bytecode -0x548ba451e66124b>)(((#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 22/22 0x1579e4b17db1> :registered-server-capabilities (#s(lsp--registered-capability :id "id" :method "workspace/didChangeWatchedFiles" :options #<hash-table equal 1/1 0x1579e4a5ca9d>)) :root "/home/lassemaatta/work/vaahtera" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn workspace) #<bytecode 0x13767afd27dfe91d>) :test? lsp-clojure--build-command) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 1/65 0x1579e34c50c3> :request-handlers #<hash-table equal 0/65 0x1579e3692797> :response-handlers #<hash-table eql 0/65 0x1579e336f6ed> :prefix-function nil :uri-handlers #<hash-table equal 1/65 0x1579e4742535> :action-handlers #<hash-table equal 1/65 0x1579e33b6191> :major-modes (clojure-mode clojurec-mode clojurescript-mode clojure-ts-mode) :activation-fn nil :priority 0 :server-id clojure-lsp :multi-root nil :initialization-options (:dependency-scheme "jar" :show-docs-arity-on-same-line? t) :semantic-tokens-faces-overrides (:types (("macro" . font-lock-keyword-face) ("keyword" . clojure-keyword-face) ("event" . default))) :custom-capabilities ((experimental (testTree . t))) :library-folders-fn #f(compiled-function (workspace) #<bytecode -0x47e1d70f7d62878>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x1579e1e75427> :download-server-fn #f(compiled-function (client callback error-callback update?) #<bytecode -0x15a151ffef4f9f07>) :download-in-progress? nil :buffers nil :synchronize-sections nil) :host-root nil :proc #<process clojure-lsp> :cmd-proc #<process clojure-lsp> :buffers (#<buffer core.clj> #<buffer app_form_util.clj> #<buffer set_work_i_test.clj> #<buffer fixture.clj> #<buffer api_test.clj> #<buffer app_work_util.clj>) :semantic-tokens-faces nil :semantic-tokens-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x1579e1759b8f> :watches #<hash-table equal 0/65 0x1579e1759baf> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 118/145 0x1579e187cc8d> :work-done-tokens #<hash-table equal 0/65 0x1579e187ccad>) . [#<hash-table equal 3/3 0x1579e5579899> #<hash-table equal 3/3 0x1579e557998d> #<hash-table equal 3/3 0x1579e5579a6d> #<hash-table equal 3/3 0x1579e5579b4d> #<hash-table equal 3/3 0x1579e5579c2d> #<hash-table equal 3/3 0x1579e5579d21> #<hash-table equal 3/3 0x1579e5579e01> #<hash-table equal 3/3 0x1579e5579ee1> #<hash-table equal 3/3 0x1579e5579fc1> #<hash-table equal 3/3 0x1579e557a0a1>])))
  #f(compiled-function (result) #<bytecode 0x4308005247cafee>)([#<hash-table equal 3/3 0x1579e5579899> #<hash-table equal 3/3 0x1579e557998d> #<hash-table equal 3/3 0x1579e5579a6d> #<hash-table equal 3/3 0x1579e5579b4d> #<hash-table equal 3/3 0x1579e5579c2d> #<hash-table equal 3/3 0x1579e5579d21> #<hash-table equal 3/3 0x1579e5579e01> #<hash-table equal 3/3 0x1579e5579ee1> #<hash-table equal 3/3 0x1579e5579fc1> #<hash-table equal 3/3 0x1579e557a0a1>])
  #f(compiled-function (result) #<bytecode 0xaec9a24bc4c1b25>)([#<hash-table equal 3/3 0x1579e5579899> #<hash-table equal 3/3 0x1579e557998d> #<hash-table equal 3/3 0x1579e5579a6d> #<hash-table equal 3/3 0x1579e5579b4d> #<hash-table equal 3/3 0x1579e5579c2d> #<hash-table equal 3/3 0x1579e5579d21> #<hash-table equal 3/3 0x1579e5579e01> #<hash-table equal 3/3 0x1579e5579ee1> #<hash-table equal 3/3 0x1579e5579fc1> #<hash-table equal 3/3 0x1579e557a0a1>])
  lsp--parser-on-message(#<hash-table equal 3/3 0x1579e557984b> #s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 22/22 0x1579e4b17db1> :registered-server-capabilities (#s(lsp--registered-capability :id "id" :method "workspace/didChangeWatchedFiles" :options #<hash-table equal 1/1 0x1579e4a5ca9d>)) :root "/home/lassemaatta/work/vaahtera" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn workspace) #<bytecode 0x13767afd27dfe91d>) :test? lsp-clojure--build-command) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 1/65 0x1579e34c50c3> :request-handlers #<hash-table equal 0/65 0x1579e3692797> :response-handlers #<hash-table eql 0/65 0x1579e336f6ed> :prefix-function nil :uri-handlers #<hash-table equal 1/65 0x1579e4742535> :action-handlers #<hash-table equal 1/65 0x1579e33b6191> :major-modes (clojure-mode clojurec-mode clojurescript-mode clojure-ts-mode) :activation-fn nil :priority 0 :server-id clojure-lsp :multi-root nil :initialization-options (:dependency-scheme "jar" :show-docs-arity-on-same-line? t) :semantic-tokens-faces-overrides (:types (("macro" . font-lock-keyword-face) ("keyword" . clojure-keyword-face) ("event" . default))) :custom-capabilities ((experimental (testTree . t))) :library-folders-fn #f(compiled-function (workspace) #<bytecode -0x47e1d70f7d62878>) :before-file-open-fn nil :initialized-fn nil :remote? nil :completion-in-comments? nil :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x1579e1e75427> :download-server-fn #f(compiled-function (client callback error-callback update?) #<bytecode -0x15a151ffef4f9f07>) :download-in-progress? nil :buffers nil :synchronize-sections nil) :host-root nil :proc #<process clojure-lsp> :cmd-proc #<process clojure-lsp> :buffers (#<buffer core.clj> #<buffer app_form_util.clj> #<buffer set_work_i_test.clj> #<buffer fixture.clj> #<buffer api_test.clj> #<buffer app_work_util.clj>) :semantic-tokens-faces nil :semantic-tokens-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x1579e1759b8f> :watches #<hash-table equal 0/65 0x1579e1759baf> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 118/145 0x1579e187cc8d> :work-done-tokens #<hash-table equal 0/65 0x1579e187ccad>))
  #f(compiled-function (msg) #<bytecode -0xe022174b2dee238>)(#<hash-table equal 3/3 0x1579e557984b>)
  mapc(#f(compiled-function (msg) #<bytecode -0xe022174b2dee238>) (#<hash-table equal 3/3 0x1579e557984b> #<hash-table equal 3/3 0x1579e1204c97>))
  #f(compiled-function (proc input) #<bytecode 0xabc8b06a6767112>)(#<process clojure-lsp> "Content-Length: 1867\15\n\15\n{\"jsonrpc\":\"2.0\",\"id\":330,...")</pre>
</details>

**Comment by yyoncho** [comment]
@lassemaatta can you verify that this happens if you reinstall emacs related packages following the procedure described here: https://emacs-lsp.github.io/lsp-mode/page/performance/#use-plists-for-deserialization

**Comment by iitalics** [comment]
i don't think it's acceptable to have this package breaking if the user does not dig through the documentation and find a special compiler environment variable just for the sake of performance. please revert this behavior or make the code flexible to handle both representations

**Comment by iitalics** [comment]
the problem is that `lsp--point-to-position` returns a plist, not a Position object (hashtable). so the calls to those functions are not valid. it looks like changing `lsp--point-to-position` to not use plists requires a big refactoring effort since **lot** of other code depends on it returning plists rather than being generic over `lsp-use-plists`. until that effort is done, this patch should be reverted since its use of `lsp--point-to-position` is not correct

**Pull request merged**
