### PR TITLE
Use url-parse to extract filename #261

### PR DESCRIPTION
**Pull request by sebastiencs**
Issue #261

### CODE REVIEW

**Comment by vibhavp** [comment]
Could you look into why this fails the tests?

**Comment by sebastiencs** [comment]
I think the tests are wrong:
```el
(should (equal (lsp--path-to-uri "c:/Users/?/") "file:///c:/Users/%3F/"))
(should (equal (lsp--uri-to-path "file:///c:/Users/%7B%7D/") "c:/Users/{}/"))
```
[link](https://github.com/emacs-lsp/lsp-mode/blob/master/test/lsp-common-test.el#L25)

Is `file:///c:/path` a valid uri ? @esbena @akermu

**Comment by akermu** [comment]
Yes it is, see https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/.

I think `url-generic-parse-url` is not a *URI*-parser.

**Comment by akermu** [comment]
Okay, reading the info nodes, the function is described as an URI-parser, so I would consider this an emacs bug in `url-generic-parse-url`.

**Comment by esbena** [comment]
For reference, here are the URI objects from the two tests, when the strings are parsed by the LSP reference URI converter: https://github.com/Microsoft/vscode-uri.

`(should (equal (lsp--path-to-uri "c:/Users/?/") "file:///c:/Users/%3F/"))`:
```
> fromPath('c:/Users/?/')
URI {
  _scheme: 'file',
  _authority: '',
  _path: '/c:/Users/?/',
  _query: '',
  _fragment: '',
  _formatted: null,
  _fsPath: null }
> fromURI('file:///c:/Users/%3F/')
URI {
  _scheme: 'file',
  _authority: '',
  _path: '/c:/Users/?/',
  _query: '',
  _fragment: '',
  _formatted: null,
  _fsPath: null }
```

`(should (equal (lsp--uri-to-path "file:///c:/Users/%7B%7D/") "c:/Users/{}/"))`: 
```
> fromURI('file:///c:/Users/%7B%7D/')
URI {
  _scheme: 'file',
  _authority: '',
  _path: '/c:/Users/{}/',
  _query: '',
  _fragment: '',
  _formatted: null,
  _fsPath: null }
> fromPath('c:/Users/{}/')
URI {
  _scheme: 'file',
  _authority: '',
  _path: '/c:/Users/{}/',
  _query: '',
  _fragment: '',
  _formatted: null,
  _fsPath: null }
```
As you can see, the resulting URI objects are equivalent, so the tests are correct as is.

**Comment by sebastiencs** [comment]
Sorry, I'm a bit lost with your comment @esbena.
As I understand it, `vscode-uri` parse the same way that does `url-generic-parse-url`.

From your results (with vscode-uri):
`file:///c:/Users/%7B%7D/` -> `/c:/Users/{}/`  
with url-generic-parse-url:
`file:///c:/Users/%7B%7D/` -> `/c:/Users/{}/`   (same result)
But [our tests](https://github.com/emacs-lsp/lsp-mode/blob/master/test/lsp-common-test.el#L31) expect:
`file:///c:/Users/%7B%7D/` -> `c:/Users/{}/`

So whether there is a bug in both `url-generic-parse-url` and `vscode-uri`, or `emacs` and `vscode` can open files with such path: `/c:/path/file`.

That's how I interpret it, am I missing something ?

**Comment by akermu** [comment]
As `emacs` on windows does not handle a path like `/c:/pathfile` correctly, I would propose to use `url-generic-parse-url` and remove the slash on windows, if it's the first character.

**Comment by sebastiencs** [comment]
@akermu Done

**Comment by esbena** [comment]
@sebastiencs you are right, and I support @akermus suggestion and your implementation. Thank you for the work.

(
I somehow missed that there is no leading slash in the test expectation. My big bad.

> But our tests expect:
> `file:///c:/Users/%7B%7D/ -> c:/Users/{}/`

)

**Comment by vibhavp** [comment]
Merged, thanks.

**Comment by kimim** [comment]
Hello, I got this error:
```
Debugger entered--Lisp error: (args-out-of-range "" 0)
  lsp--uri-to-path-1("file://D:\\workspace\\vision\\src\\clj\\vorstellung\\routes\\home.clj")
  lsp--uri-to-path("file://D:\\workspace\\vision\\src\\clj\\vorstellung\\routes\\home.clj")
```

Is this considered in the test? I am running Emacs from MingW64:
GNU Emacs 27.1 (build 1, x86_64-w64-mingw32) of 2020-11-20

Thanks.

**Comment by kiennq** [comment]
The URI is wrong https://en.wikipedia.org/wiki/File_URI_scheme
It should be `file:///D:\\workspace\\vision\\src\\clj\\vorstellung\\routes\\home.clj` (3 slashes) since the `hostname` is empty

**Pull request merged**
