### PR TITLE
Add lsp-ltex page

### PR DESCRIPTION
**Pull request by jcs090218**
Inform new server for [lsp-ltex](https://github.com/emacs-languagetool/lsp-ltex).

### CODE REVIEW

**Review by yyoncho — APPROVED** [review]

**Comment by ericdallo** [comment]
@jcs090218 Does the CI failing is related with the changes?

**Comment by jcs090218** [comment]
> Does the CI failing is related with the changes?

Hmm... not sure why the CI fails. I have reverted for now. 😕

**Comment by jcs090218** [comment]
I guess there is something wrong with melpa? 😕 

```
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Failed to download ‘melpa’ archive.
Package refresh done
Package ‘f-0.20.0’ is unavailable
make: *** [test-downstream-pkgs] Error 255
```

**Comment by ericdallo** [comment]
It seems some inconsistency on MELPA, not related with this PR: 
image

**Comment by jcs090218** [comment]
It seems to fail on Windows and sometime on macOS... pretty random.

**Comment by jcs090218** [comment]
I have applied a fix in #2908. 👍

**Comment by jcs090218** [comment]
Can someone merge this? I don't think I am able to merge due to the fail CI.

**Pull request merged**
