### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by jcs090218**
Original #3859.

Apply the fix discussed in https://github.com/emacs-lsp/lsp-mode/pull/3859#discussion_r1051437090.

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]

**Comment by jcs090218** [comment]
@yyoncho Have you tested this patch? I think it should be good to merge. Hope I don't make another stupid mistake. 😅

**Comment by yyoncho** [comment]
I want to do some manual testing.

**Comment by jcs090218** [comment]
@yyoncho Any update?

I think this should be pretty safe to merge, basically just

- `point-at-bol` to `line-beginning-position`
- `point-at-eol` to `line-end-position` 

and the rest are styling.

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
Thank you!

**Pull request merged**
