### PR TITLE
Change typescript activation function

### PR DESCRIPTION
**Pull request by rnikoopour**
Because javascript and typescript used the same activation function it would only activate the javascript language server. 

This differentiates typescript and javascript activation functions.

### CODE REVIEW

**Comment by kiennq** [comment]
Since `javascript-typescript-language-server` and `typescript-language-server` support both `javascript` and `typescript`, why we need to differentiate between them?
Also, if you could keep the `rx` syntax, it would be great, the `rx` syntax is easier to see at a glance than the full-blown regex

**Comment by rnikoopour** [comment]
When speaking with @yyoncho I shared the following with him related to `lsp-docker`:

```(make-client :server-id 'jsts-ls :docker-server-id 'jstsls-docker :server-command "typescript-language-server --stdio")```

He responded by saying this used the wrong server.  When trying to fix that I had to make the change to `lsp-mode` to make sure that javascript used the javascript server and typescript used the typescript server.

**Comment by rnikoopour** [comment]
Going to close this for now.

**Comment by yyoncho** [comment]
> When speaking with @yyoncho I shared the following with him related to `lsp-docker`:
> 
> `(make-client :server-id 'jsts-ls :docker-server-id 'jstsls-docker :server-command "typescript-language-server --stdio")`

I meant that you use the `ts-ls` binary for `jsts-ls` server in your config.

**Pull request closed without merging**
