### PR TITLE
Switch tool detection for lsp-unzip (#3022)

### PR DESCRIPTION
**Pull request by Horrih**
It caused issues on windows if unzip was found on the PATH, because it fell back to the bash command + unzip.

Changing in order of detection fixes the issue.

### CODE REVIEW

**Comment by yyoncho** [comment]
This will force powershell on linux which IIRC was causing trouble in the past. Can you add additional condition (if on windows and if powershell there - use it)

**Comment by Horrih** [comment]
Just pushed a new version, is this what you had in mind ?
Just checked it on both my systems, it seems to work fine.

Btw, thanks a lot for your selfless work on lsp-mode.
Lsp-mode is the sole reason I came back to emacs in 2019 years after I gave up on the tags system.

**Comment by yyoncho** [comment]
> ((executable-find "powershell") lsp-ext-pwsh-script

can you keep that too in the end?

**Comment by Horrih** [comment]
Sure, is that better ?

I rebased onto master + squashed the previous commits

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
LGTM! Thank you for taking care of this!

**Pull request merged**
