### PR TITLE
Resolve npx prompting for older npx users

### LINKED ISSUE #3672: Graphql LSP doesn't install all dependencies
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

When installing graphql lsp, it runs
```bash
/usr/bin/npm -g --prefix ~/.cache/lsp/npm/graphql-language-service-cli install graphql-language-service-cli
```
However, once the server is activated, it complains about a missing module `graphql-language-service`. Installing that directly (in the terminal) fixed the issue.
```bash
/usr/bin/npm -g --prefix ~/.cache/lsp/npm/graphql-language-service-cli install graphql-language-service
```

I'd make a pull request, but I thought it best to report and let the experts do it. :smile: 

### Steps to reproduce

- Open a graphql file
- run `M-x lsp`
- Confirm the default lsp on the prompt

I immediately got that message saying the server exited and suggesting I check the stderr buffer.

### Expected behavior

The mode would turn on without erros

### Which Language Server did you use?

graphql-language-service

### OS

Linux

### Error callstack

_No response_

### Anything else?

Issue is fixed by installing graphql-language-service

### PR DESCRIPTION
**Pull request by elken**
Might need testing by other users, it worked in isolation for me.

Fixes #3672

### CODE REVIEW

**Review by yyoncho — APPROVED** [review]

**Review by ericdallo — APPROVED** [review]

**Comment by elken** [comment]
Just waiting for confirmation from the affected users :smile: otherwise will merge in a couple of days

**Review by jcs090218 — APPROVED** [review]
Tested on Windows. 👍

**Comment by elken** [comment]
> Tested on Windows. +1

With what version of npm? The key was people using node 14 and earlier.

**Comment by jcs090218** [comment]
> With what version of npm? The key was people using node 14 and earlier.

`v16.15.0`. I generally use LTS.

**Comment by jcs090218** [comment]
Might be great if we have activation/installation test for servers, these are tests I think it should be helpful for this kind of scenario.

- [lsp-grammarly/activate.yml](https://github.com/emacs-grammarly/lsp-grammarly/blob/master/.github/workflows/activate.yml) - test for installation and run the language server afterward.
- [lsp-ltex/activate.yml](https://github.com/emacs-languagetool/lsp-ltex/blob/master/.github/workflows/activate.yml) - same idea as above.

**Comment by elken** [comment]
> Might be great if we have activation/installation test for servers, these are tests I think it should be helpful for this kind of scenario.
> 
>     * [lsp-grammarly/activate.yml](https://github.com/emacs-grammarly/lsp-grammarly/blob/master/.github/workflows/activate.yml) - test for installation and run the language server afterward.
> 
>     * [lsp-ltex/activate.yml](https://github.com/emacs-languagetool/lsp-ltex/blob/master/.github/workflows/activate.yml) - same idea as above.

I remember having a discussion about those before, I think there's a great benefit to adding them.

**Comment by jcs090218** [comment]
> I remember having a discussion about those before, I think there's a great benefit to adding them.

Found it, link https://github.com/emacs-lsp/lsp-mode/discussions/3608

**Comment by elken** [comment]
> > I remember having a discussion about those before, I think there's a great benefit to adding them.
> 
> Found it, link #3608

I mean specifically around activation tests, but yeah that discussion has been something I've meant to action for some time.

**Pull request merged**
