### PR TITLE
Various fixes to lsp-fsharp

### PR DESCRIPTION
**Pull request by drvink**
Changes described in the commit messages and docstrings.

### CODE REVIEW

**Comment by razzmatazz** [comment]
hey @drvink I am thinking about reviewing/testing this, but my question is about your last commit

I was planning about introducing an ability to install fsautocomplete as a global dotnet tool (as I am doing it for csharp-ls). in your case you apparently are trying to use the locally installed fsautocomplete dotnet tool

is there any particular reason you expect fsautocomplete to be installed as a local dotnet tool and not as a global dotnet tool? as I understand the current installation method for fsharp fails for you too, right?

**Comment by razzmatazz** [comment]
also, I don't quiet get the reason behind introducing `lsp-use-workspace-root-for-server-default-directory` var? is this because you're using a "local" version of fsautocomplete dotnet tool and not a global? i.e. in the case of local dotnet too you only have access to the command from workspace root, right?

then I guess this wouldn't be necessary if we require fsautocomplete to be installed as a global tool

**Comment by drvink** [comment]
Indeed, I didn't add anything for installing it; it would be even simpler than the existing install code, since as of 0.50, FSAC is intended to be installed as a dotnet tool (and only a nupkg is provided in the github releases, no more zip file). I figured I'd get this PR through first, since it doesn't break anything or change any defaults.

I agree the ideal thing would be to try to run it as a global tool by default. However, when I installed fsautocomplete as a global tool, it still didn't work unless I manually made a `dotnet-fsautocomplete` symlink pointing to the FSAC binary somewhere in my `PATH`, and then I could run it via `dotnet fsautocomplete` (global tools can't be run with `dotnet tool`). I don't know if we should make the symlink as part of installation from `lsp-mode`--it would probably be rude to do it automatically, because there's no location that's both guaranteed to be in the user's `PATH` and where it would not be presumptuous to mess with its contents. But we should definitely at least tell the user they have to do it, if not.)

I don't think it hurts to keep `lsp-fsharp-use-dotnet-tool-for-fsac` and just leave it nil by default, given that people may want it local for any number of reasons.

(I wonder: should we try fallbacks? E.g. try `dotnet tool run` iff `lsp-fsharp-use-dotnet-tool-for-fsac` is non-nil; else (or if it fails) try `dotnet fsautocomplete` (global); else try the old way. I couldn't find an easy way to do it, but it's probably not worth it anyway.)

And yes, you only have access to local dotnet tools if you're in a directory under the workspace root, so I had to add the stuff for `lsp-use-workspace-root-for-server-default-directory` in order for lsp-mode to be able to run it. I could easily imagine a situation like this coming up again in the future (including with other lsp servers/language "package" systems), so I think it's useful to keep even if your plan is to just install FSAC as a global tool.

**Comment by razzmatazz** [comment]
ok, my plan is then to:
(a) use your first 2 commits as a base for my PR
(b) rewrite installation/startup mechanism to use global tool version
(c) leave it to you to rebase your last PR so you can provide customization on top of (b)

**Comment by razzmatazz** [comment]
@drvink I have upped a PR https://github.com/emacs-lsp/lsp-mode/pull/3350 with your commits (sans the last one)

I suggest we wait for it to be merged and then you can reapply your last commit with non-global fsautocomplete setup on top of master then

**Comment by drvink** [comment]
@razzmatazz Do you want me to try to rebase what I have on #3350, or should I wait until it's merged?

**Comment by razzmatazz** [comment]
> @razzmatazz Do you want me to try to rebase what I have on #3350, or should I wait until it's merged?

Actually, could you wait a bit -- I got my pc reinstalled twice -- sorry it took so long -- as I still want to add `(executable-find "fsautocomplete")` check to inform the user he/she has to fix `exec-path` before merge

should be able to do it today

**Comment by razzmatazz** [comment]
I have enabled automerge on #3350, should be merged soon after CIs are complete

**Comment by elken** [comment]
Might also be worth adding in [`defcustom-lsp`](https://github.com/emacs-lsp/lsp-mode/pull/3167)

**Comment by yyoncho** [comment]
can you resolve conflicts?

**Comment by drvink** [comment]
@yyoncho Sorry to keep you waiting; rebased and should be fine to merge now.

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
@drvink thank you. 

(FTR it is good to ping after force push, GH might not send a mail)

**Pull request merged**
