### PR TITLE
Provide trigger character hint to company-mode

### PR DESCRIPTION
**Pull request by tigersoldier**
If the server provides trigger characters and the point is after one of them,
set :company-prefix-length to t so that company-capf always shows completion
candidates regardless the actual length of the prefix (which is likely to be 0).

### CODE REVIEW

**Comment by bkchr** [comment]
Works for me :) 

@vibhavp anything against merging? :)

**Comment by vibhavp** [comment]
No issues as such, but this ends up adding a soft dependency on company-mode, right?

**Comment by bkchr** [comment]
You mean that it only works with company? Yeah you are probably right. Maybe the annotation could be made configurable

**Comment by tigersoldier** [comment]
@vibhavp It does provide company-only feature, since trigger character doesn't make sense to completion-at-point.

@bkchr I'm on the fence whether to add a custom variable to toggle it. It doesn't take much time to get the trigger characters. IMO it's not a good experience to have a long list of customizable settings for every tiny details.

**Comment by bkchr** [comment]
@tigersoldier I came across your https://github.com/tigersoldier/company-lsp project. I think, if that supports the trigger characters for company, it is okay to not merge the feature into lsp-mode directly.
While looking over your code, I saw that some functionality like:
`(advice-add 'lsp--parser-on-message :after 'company-lsp--on-message)`
Could be integrated into lsp-mode by providing a hook instead of hacking into the process.

**Comment by sebastiencs** [comment]
> While looking over your code, I saw that some functionality like:
(advice-add 'lsp--parser-on-message :after 'company-lsp--on-message)
Could be integrated into lsp-mode by providing a hook instead of hacking into the process.

My fault, I've wrote that functionality. I didn't know the code of lsp-mode enough to make a PR to support async.
But it seems that there is now a PR for this purpose: https://github.com/emacs-lsp/lsp-mode/pull/138

**Comment by bkchr** [comment]
@sebastiencs yeah no problem! :) Just thought loud about how the projects could be working together :)

**Comment by tigersoldier** [comment]
@bkchr I agree both projects can work better together and would love to push features upstream. Just wanted to get the feature landed quickly so I can use it :)

Back to the topic of this PR. My original plan was to implement all company-related feature here and just deprecate company-lsp in favor of `company-capf`. Now company-lsp is implementing some features that are hard to port to completion-at-point-function (e.g async completion, post-completion actions), the original goal is no longer feasible.

Let's close this PR.

**Comment by vibhavp** [comment]
@tigersoldier I've added support for async requests in b56a06e5ca4cf01b126521183d2820745b06f63f. If that helps, `company-lsp` should use it instead of advising internal functions.

**Comment by tigersoldier** [comment]
Sure, I'll update it.

**Pull request closed without merging**
