### PR TITLE
Accept -1 to ignore version for document changes

### PR DESCRIPTION
**Pull request by timfel**
This is what the netbeans lsp server sends.

### CODE REVIEW

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
Maybe we can change it of `(<= verison 0)`?

**Comment by timfel** [comment]
> Maybe we can change it of `(<= verison 0)`?

I don't mind, I wasn't sure what a valid version is :)

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
> This is what the netbeans lsp server sends.

Willing to provide a PR for that server as well?

**Comment by timfel** [comment]
> > This is what the netbeans lsp server sends.
> 
> Willing to provide a PR for that server as well?

I'm working on it, yes :)

**Pull request merged**
