### PR TITLE
lsp-rust WIP: Add rust-analyzer trace server option

### PR DESCRIPTION
**Pull request by apiraino**
Hi @brotzeit can you help me refine and finish this PR? I can't code in lisp :-)

I'd love to contribute a bit to #1559 , I need to trace the rust-analyzer server but I dont know how to go on from here.

My reference for the trace option is [here](https://github.com/rust-analyzer/rust-analyzer/blob/09b8ee30bab7040ec983968aaca90814029f4dc0/editors/code/package.json#L363)

thank you so much!

### CODE REVIEW

**Comment by kiennq** [comment]
What's the additional information this one will log compare to set `lsp-log-io` to `t`?

**Comment by apiraino** [comment]
> What's the additional information this one will log compare to set `lsp-log-io` to `t`?

Could be but I have no idea :-) I'm still figuring out all the available options. I've been suggested to do so to increase the amount of info when I need to debug and provide useful info what's happening. 

But now that I look closely at the standard `lsp-mode` options I see a `lsp-server-trace` flag and it seems to do what I need. If yes, I can happily close this PR as it's not really needed.

**Comment by apiraino** [comment]
ok, after some more tests, I've understood that this feature is already implemented (silly me that I did not read more carefully the documentation)

**Comment by brotzeit** [comment]
@apiraino No problem. Can you do me a favor and test  #1568

**Pull request closed without merging**
