### PR TITLE
Separate symbol highlighting from eldoc.

### PR DESCRIPTION
**Pull request by sebastiencs**
Symbol highlight was depending on eldoc function.
If the user or another package change
eldoc-documentation-function (which lsp-ui-doc do), the symbol
highlighting was lost.

### CODE REVIEW

**Comment by vibhavp** [comment]
Adding `lsp-highlight` to `post-command-hook` is inefficient, as that would call the function even at points when we don't want it to.

IMO, a better way to do this would be to create a new idle timer with `secs` = `eldoc-idle-delay`, so as to sync with eldoc behavior, and make the timer function process symbol highlights.

**Comment by sebastiencs** [comment]
Eldoc itself does the same thing (adding `eldoc-schedule-timer` to `post-command-hook`).
> that would call the function even at points when we don't want it to.

It would call the function as many times as `lsp--on-hover`.
It isn't more inefficient than eldoc is.

> IMO, a better way to do this would be to create a new idle timer with secs = eldoc-idle-delay, so as to sync with eldoc behavior, and make the timer function process symbol highlights.

I'm not sure to understand your point, if you mean create a timer with a non-nil `repeat`, that would call the function even more than with `post-command-hook` (when the point hasn't changed its position)

**Comment by vibhavp** [comment]
> Eldoc itself does the same thing (adding eldoc-schedule-timer to post-command-hook).

Ah, I was under the impression that eldoc used an idle timer to show documentation (which is what flycheck does). Nevermind.

**Comment by sebastiencs** [comment]
I rebased my branch. It should be good

**Comment by sebastiencs** [comment]
@vibhavp Any concern about this PR ?

**Comment by yyoncho** [comment]
@sebastiencs do you still want to merge the PR, if so, can you resolve the conflicts?

**Comment by MaskRay** [comment]
I have an eldoc refactor https://github.com/emacs-lsp/lsp-mode/pull/448

**Comment by yyoncho** [comment]
Closing in favour of #448

**Pull request closed without merging**
