### PR TITLE
docs(terraform): add terraform-ls page

### PR DESCRIPTION
**Pull request by elken**

### CODE REVIEW

**Review by yyoncho — APPROVED** [review]

**Comment by elken** [comment]
@yyoncho I don't have write access so you'll have to merge if you're happy with it :)

**Comment by yyoncho** [comment]
@elken I added you to lsp-mode team, let me know if it works.

**Comment by elken** [comment]
> @elken I added you to lsp-mode team, let me know if it works.

Yup I can merge now :) Squash by default?

**Comment by yyoncho** [comment]
Yes.

**Pull request merged**
