### PR TITLE
Add methods to convert from a URI to a path and vice versa

### PR DESCRIPTION
**Pull request by akermu**
Solves #227

### CODE REVIEW

**Comment by vibhavp** [comment]
Thanks for the PR, could you add a few tests for these functions to `tests/lsp-common-tests.el`?

**Comment by akermu** [comment]
I added tests. Please wait before you merge this, as I am not sure anymore if `url-hexify-string` and `url-unhex-string` are doing the right thing. I'll have to read the RFC.

**Comment by akermu** [comment]
Okay I'm confident that those functions do the right thing. Can you restart the CI please, as it failed to build emacs!

**Comment by akermu** [comment]
Okay travis fails to compile emacs, probably because of some Meltdown/Spectre mitigation..

**Comment by vibhavp** [comment]
Thanks.

**Pull request merged**
