### PR TITLE
Workaround new Eldoc on Emacs 27  

### LINKED ISSUE #3295: eldoc with lsp-mode no longer works in Emacs 27.2
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

It seems like with the latest changes ElDoc has stopped working. I see the PR merged https://github.com/emacs-lsp/lsp-mode/pull/3275 that is suspect. There is no ElDoc showing, and when I try to run `eldoc-mode` in the LSP buffer, it tells me that it is not supported in that buffer.

### Steps to reproduce

1. Use emacs 27.2
2. Use lsp-mode and typescript-mode
3. Ensure eldoc is turned on for lsp-mode
4. Nothing shows

There are no errors, diagnostic messages, or anything else really abnormal.

### Expected behavior

Expect to see ElDoc for things hovered over at point.

### Which Language Server did you use?

`ts-ls`

### OS

MacOS

### Error callstack

_No response_

### Anything else?

My LSP config

```elisp
(defun lsp-js-config ()
  "Setup lsp javascript flycheck checking."
  (flycheck-add-next-checker 'lsp 'javascript-eslint)
  (setq-local lsp-diagnostics-provider :none)
  (setq-local lsp-ui-sideline-show-code-actions nil))
(defun lsp-rust-config ()
  "Setup lsp rust specific configs."
  (setq lsp-rust-analyzer-cargo-watch-command "clippy")
  (setq-local lsp-eldoc-render-all t)
  (setq-local lsp-idle-delay 0.6)
  (setq lsp-rust-analyzer-server-display-inlay-hints t))
(defun lsp-ui-rust-config ()
  "Setup lsp ui rust specific configs."
  (setq-local lsp-ui-peek-always-show t)
  (setq-local lsp-ui-sideline-show-hover t)
  (setq-local lsp-ui-doc-enable nil)
  (setq-local lsp-enable-file-watchers t)
  (setq-local lsp-modeline-diagnostics-enable t))
(defun lsp-typescript-config ()
  "Setup lsp typescript config"
  (flycheck-add-next-checker 'lsp 'javascript-eslint))
(use-package lsp-mode
  :ensure t
  :diminish
  :after (flycheck)
  :hook ((c++-mode python-mode lua-mode typescript-mode js-mode) . lsp)
  :commands lsp
  :config
  (progn
    (setq lsp-enable-snippet nil)
	(setq lsp-auto-guess-root t)
    (setq lsp-enable-file-watchers nil)
	(setq lsp-headerline-breadcrumb-enable nil)
	(setq lsp-enable-text-document-color nil)
	(setq lsp-semantic-tokens-enable nil)
	(setq lsp-modeline-code-actions-enable nil)
	(setq lsp-modeline-diagnostics-enable nil)
	(add-hook 'js-mode-hook #'lsp-js-config)
	(add-hook 'rustic-mode-hook #'lsp-rust-config)
	(add-hook 'typescript-mode-hook #'lsp-typescript-config)))
(use-package lsp-ui
  :ensure t
  :after (lsp-mode)
  :commands lsp-ui-mode)
(use-package lsp-treemacs
  :ensure t
  :after (treemacs)
  :commands lsp-treemacs-errors-list)
(use-package lsp-ivy
  :ensure t
  :after (counsel)
  :commands lsp-ivy-workspace-symbol)
```

I also deleted the lsp and eldoc folders from `~/emacs.d/elpa` and restarted.

I am guessing that the `eldoc` being pulled from elpa (1.11) is not being used. I might be able to do similar workarounds as what I have to do with `org-mode` now, so I can try that later .. but I wanted to report this.

### PR DESCRIPTION
**Pull request by daanturo**
Fixes #3295

Alternatively, there's another approach which does approximately what eglot enforces: https://github.com/daanturo/lsp-mode/commit/7091e130b22466a58e2b89b864c83b9f3223cc38

### CODE REVIEW

**Comment by yyoncho** [comment]
Do we need (eldoc "1.11") dependency for 27.1?

Also, can you fix the CI?

**Comment by daanturo** [comment]
>Do we need (eldoc "1.11") dependency for 27.1?

I think so, 27.1's eldoc doesn't have `eldoc-documentation-functions`, but isn't that version required by #3275?

BTW, I have simplified the workaround to just setting to `eldoc-documentation-default`, disregarding user's custom for Emacs < 28.

>fix the CI?

That's tough, it keeps giving this error for Emacs <=27:
```
In toplevel form:
lsp-mode.el:9320:1:Error: the function ‘eldoc-documentation-default’ is not known to be defined.
```
Maybe the new eldoc isn't provided in the CI environment.

**Comment by yyoncho** [comment]
Have you tested that it works on 27.1? If yes we can fix the ci with something like `(defvar eldoc-documentation-default)` but I am not sure if loading the elpa eldoc is enforced.

**Comment by daanturo** [comment]
> Have you tested that it works on 27.1? If yes we can fix the ci with something like `(defvar eldoc-documentation-default)` but I am not sure if loading the elpa eldoc is enforced.

Yes it's working on 27.2 but I haven't tested against 26.3.
Thanks to the `defvar`, CI is finally happy.

**Comment by daanturo** [comment]
Thanks fully it's working on Emacs 26.3, too, at least for clangd.

image

**Comment by yyoncho** [comment]
Thank you for working on that!

**Pull request merged**
