### PR TITLE
Use auto-begin fro company

### PR DESCRIPTION
**Pull request by jcs090218**
Response to #2584.

@dgutov @kiennq

### CODE REVIEW

**Comment by kiennq** [comment]
It doesn't seem to work though? @dgutov
I've tried with same repro step, as original bug, only switch to use `(run-at-time nil nil (lambda () (company-auto-begin)  (company-post-command)))`. However, the popup isn't showing up like the case of using `company-complete`

**Review by kiennq — CHANGES_REQUESTED** [review]
It doe

**Comment by dgutov** [comment]
Yes, sorry. `company-post-command` includes a check for `this-command`, so try this:

```el
(run-at-time 0 nil
             (lambda ()
               (company-auto-begin)
               (let ((this-command 'company-idle-begin))
                 (company-post-command))))
```

**Comment by kiennq** [comment]
Thanks, the code does look more complicated.
Is there draw back of using `company-complete` here?

**Comment by jcs090218** [comment]
Sorry I have accidentally remove my previous branch.

Move PR to #2593.

**Comment by dgutov** [comment]
> Thanks, the code does look more complicated.

FWIW, the `this-command` value is arbitrary; it just shouldn't be nil.

> Is there draw back of using company-complete here?

The only reason `company-complete` works here is that it explicitly changes `this-command` as well (to `company-complete-common`). As for why it's undesirable: it calls the aforementioned `company-complete-common`. Which is likely to surprise the user, though it's only noticeable when all completions have a common prefix.

Really, it's a user-level, dwim-ish command, it's not designed for use in a Lisp program.

**Pull request closed without merging**
