### PR TITLE
lsp-rust: use array type for lsp-rust-features

### LINKED ISSUE #844: Error during RLS configuration
**Describe the bug**
Rust RLS 1.34.0 can't be configured because of the error:
```
[2019-05-21T13:20:25Z WARN  rls::actions::notifications] Received unactionable config: Object({"rust": Object({"all_features": Bool(false), "all_targets": Bool(true), "build_bin": Null, "build_command": Null, "build_lib": Null, "build_on_save": Bool(false), "cfg_test": Bool(false), "clear_env_rust_log": Bool(true), "clippy_preference": String("opt-in"), "features": Null, "full_docs": Null, "jobs": Null, "no_default_features": Bool(false), "racer_completion": Bool(true), "rustflags": Null, "rustfmt_path": Null, "show_hover_context": Bool(true), "show_warnings": Bool(true), "sysroot": String(""), "target": String(""), "target_dir": Null, "unstable_features": Bool(false), "use_crate_blacklist": Bool(true), "wait_to_build": Number(1500)})}) (error: ())
[2019-05-21T13:20:25Z DEBUG rls::server] Error handling notification: RawMessage { method: "workspace/didChangeConfiguration", id: Null, params: Object({"settings": Object({"rust": Object({"all_features": Bool(false), "all_targets": Bool(true), "build_bin": Null, "build_command": Null, "build_lib": Null, "build_on_save": Bool(false), "cfg_test": Bool(false), "clear_env_rust_log": Bool(true), "clippy_preference": String("opt-in"), "features": Null, "full_docs": Null, "jobs": Null, "no_default_features": Bool(false), "racer_completion": Bool(true), "rustflags": Null, "rustfmt_path": Null, "show_hover_context": Bool(true), "show_warnings": Bool(true), "sysroot": String(""), "target": String(""), "target_dir": Null, "unstable_features": Bool(false), "use_crate_blacklist": Bool(true), "wait_to_build": Number(1500)})})}) }
```

At the same time it accepts `(:rust (:clippy_preference "on" :build_on_save t)) params so it seems one of default config options breaks it.

**To Reproduce**
Just run lsp on any rust project. To see this error set `RUST_LOG=rls=debug` environment variable.

**Which Language Server did you use**
lsp-rust

**OS**
Arch Linux

### PR DESCRIPTION
**Pull request by kurnevsky**
Fixes #844

### CODE REVIEW

**Comment by kurnevsky** [comment]
Ugh... It seems (vector string) defines only vector with one element, according to https://www.gnu.org/software/emacs/manual/html_node/elisp/Composite-Types.html

**Comment by yyoncho** [comment]
Thank you for contributing to `lsp-mode` and congrats for your first `lsp-mode` PR! :tada:

**Comment by GoingFast** [comment]
@kurnevsky @yyoncho not sure if its some package conflict (using company-lsp and lsp-ui) but it disabled flycheck for me, doesnt flycheck. had to undo the change and its all fine again

**Comment by yyoncho** [comment]
I suspect that the correct fix might be to revert this PR and filter the nil values before sending configuration and  thus avoid the #844

**Pull request merged**
