### PR TITLE
Signature posframe support

### PR DESCRIPTION
**Pull request by yyoncho**
----

#

### CODE REVIEW

**Comment by muirdm** [comment]
Looks cool. The posframe seemed to bounce around with point - can it stay anchored to the start of the function call? I also had trouble customizing the colors on the posframe. I customized `tooltip` face, but it didn't really work.

**Comment by yyoncho** [comment]
> - can it stay anchored to the start of the function call?

The server does not provide that data. VScode also moves the popup.

> I also had trouble customizing the colors on the posframe. I customized tooltip face, but it didn't really work.

I will expose the posframe params before merging.

**Comment by kiennq** [comment]
@yyoncho  Is there any other problem for this?

**Comment by yyoncho** [comment]
> @yyoncho Is there any other problem for this?

I think that I was planning to add some customization which is not possible ATM.

**Comment by FelipeLema** [comment]
is this posframe displayed on request? on timeout? both? either?

**Comment by yyoncho** [comment]
> is this posframe displayed on request? on timeout? both? either?

When you press signatureHelp triggerChar (e. g. `(`)/

**Comment by yyoncho** [comment]
I tested the latest version and it seems like it is working fine, except the fact that you cannot scroll the signature window screen(which will be addressed).

**Comment by yyoncho** [comment]
> > except the fact that you cannot scroll the signature window screen
> 
> @yyoncho Is there anywhere tracking that work?

@benbot afaik no

**Pull request merged**
