### PR TITLE
Add macros to add and remove a project root from the whitelist

### PR DESCRIPTION
**Pull request by alanz**
As an alternative to putting this in the enable function, as to my previous (ignored) PRs

### CODE REVIEW

**Comment by bkchr** [comment]
Where would you call this macro?
`lsp-project-whitelist` is nil by default, where do you initialize the variable?

**Comment by alanz** [comment]
It is a `defcustom` variable, see https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-methods.el#L131

So you mean the code needs to cater for the initial nil case?

**Comment by bkchr** [comment]
I would think so, but I'm no elisp expert. If you tried and it works for you, then it should be okay :)

What I wanted to ask with my first question, this `cl-defmacro` means that you would need to instantiate the macro. I wanted to know where you would need to instantiate the macro? 

Also I think, that this function don't need to be instantiated per supported language. Something like `lsp-whitelist-project`should be okay? `lsp-whitelist-project-remove` for the other case?

**Comment by alanz** [comment]
It is defined per language, haskell version is https://github.com/alanz/lsp-haskell/blob/manage-whitelist/lsp-haskell.el#L258

**Comment by bkchr** [comment]
Do you think it is important to have it per language? I think one for all should be okay.

**Comment by alanz** [comment]
Well, the key thing is to find the project root, which is specific to the language

Editing a whitelist by hand otherwise is too much of a pain. In my opinion.

**Comment by bkchr** [comment]
Yeah that would be a pain, you are right. Then I would recommend to instantiate your macros by `lsp-define-stdio-client` and `lsp-define-tcp-client`. So, the functions are automatically defined for each supported language :)

**Comment by alanz** [comment]
If you can show me how to define more than one top-level macro at a time, I
will gladly do it.

**Comment by alanz** [comment]
And I just deleted the whitelist from my custom settings and added a project. It worked fine. So `nil` initial value seems not to be a problem.

**Comment by bkchr** [comment]
Maybe @vibhavp has an opinion or idea on how to call a macro inside of a macro :D

**Comment by vibhavp** [comment]
Nah, I'm clueless about this :/
@alanz I thought your whitelist PR was still WIP, so I chose to comment once it was completed. Sorry about that.

**Comment by alanz** [comment]
@vibhavp Ok, I will rebase my original then, and request a review

**Comment by bkchr** [comment]
Okay, after fighting with lisp, I finally got something working:

```diff --git a/lsp-mode.el b/lsp-mode.el
index a806d1c..5ff4767 100644
--- a/lsp-mode.el
+++ b/lsp-mode.el
@@ -133,10 +133,15 @@ Optional arguments:
 
 `:initialize' is a function called when the client is intiailized. It takes a
  single argument, the newly created client."
-  (let ((enable (intern (format "%s-enable" name))))
-    `(defun ,enable ()
+   (let ((enable (intern (format "%s-enable" name))))
+    `(progn
+    (lsp-define-whitelist-enable ,name ,get-root)
+    (lsp-define-whitelist-disable ,name ,get-root)
+
+    (defun ,enable ()
        ,docstring
        (interactive)
+       (lsp-define-whitelist-disable ,name ,get-root)
        (let ((client (make-lsp--client
                        :language-id (if ,language-id-fn ,language-id-fn #'(lambda (_) ,language-id))
                        :send-sync #'lsp--stdio-send-sync
@@ -155,7 +160,7 @@ Optional arguments:
                (progn
                  (lsp-mode 1)
                  (lsp--start client ,extra-init-params))
-               (message "Not initializing project %s" root))))))))
+               (message "Not initializing project %s" root)))))))))
 
 (cl-defmacro lsp-define-tcp-client (name language-id get-root command host port
                                      &key docstring
```

Could apply this patch and try? This generates the add/remove function while evaluating the main macro.

**Comment by alanz** [comment]
I can try, but do not hold out much hope. An earlier version I tried looked like that, and did not work.

I cam to the conclusion that you can only define one macro per top level call

**Comment by bkchr** [comment]
No, the functions are declared for me and I can call them :) But the whitelisting does not work for me :D

**Comment by alanz** [comment]
ok, will give it a try. A bit later.

**Comment by alanz** [comment]
@bkchr your patch works, great.

But I am going to go back to my original approach insteead

**Comment by bkchr** [comment]
I would like this new approach. Your old approach introduces a new client and that needs to be implemented for each new/old language. I would propose to use this new approach, as no changes to the language plugins is required.

**Comment by alanz** [comment]
Yes, I intend using your example to make the necessary functions for my approach in https://github.com/emacs-lsp/lsp-mode/pull/173, since @vibhavp  has stated that he is OK with that concept

**Comment by alanz** [comment]
Superseded by https://github.com/emacs-lsp/lsp-mode/pull/190

**Pull request closed without merging**
