### PR TITLE
fix: nixd option groups and documentation page

### PR DESCRIPTION
**Pull request by breitnw**
My last PR (#4593) seemed to cause some documentation issues, since a few of the options were assigned to `'lsp-nix-nil` instead of `'lsp-nix-nixd`. Also, lsp-clients.json listed both nixd and rnix under a "nix" page, when they should be split into pages named "nix-nixd" and "nix-rnix", respectively.

### CODE REVIEW

**Comment by breitnw** [comment]
I do think that might make things clearer, I felt there were quite a few moving parts in that file (that's why I got the groups confused, lol 😵‍💫) Thank you for your review!

**Comment by jcs090218** [comment]
There are compile warnings in this PR:

```
In toplevel form:
lsp-nix.el:79:2: Warning: custom-declare-variable `lsp-nix-nixd-nixos-options-expr' docstring wider than 80 characters
lsp-nix.el:90:2: Warning: custom-declare-variable `lsp-nix-nixd-home-manager-options-expr' docstring wider than 80 characters
```

**Comment by psibi** [comment]
Ah, I didn't notice it and can't still find the logs in github actions. CC: @breitnw Can you open a new PR fixing the docstring warnings ?

I wonder if we should fail the CI if those check. I think I have something like that enabled for one of my projects, but I think for a project this big we would have a bunch of warnings like that which needs to be fixed.

**Comment by jcs090218** [comment]
> I wonder if we should fail the CI if those check. I think I have something like that enabled for one of my projects, but I think for a project this big we would have a bunch of warnings like that which needs to be fixed.

Agreed! We can set `byte-compile-error-on-warn` to `t` in the Eask-file. :)

**Pull request merged**
