### PR TITLE
lsp-completion: use last results in case of interrupted by keyboard

### LINKED ISSUE #1894: company-mode should not hide the dialog when lsp-mode does not have the time handle the call
At this point `lsp-mode` returns `nil` to `company-mode` when the server was not
able to respond and the user has started typing. This is a workaround of capf
being synchronous. This triggers hiding of completion dialog which later it
displayed again if there is completion result for the longer prefix. We should
eliminate that.

Potential fixed:

1. Throwing something that company-mode expects and it will be treated like "keep
   the dialog open"
2. Implementing traditional(not capf) async company backend. I suspect that the
   described issue does not exist in that case.
3. We may try to return the previous available result. Not sure if this will
   work but we do that on other places like eldoc-mode to avoid blinking.

cc @dgutov @kiennq

### PR DESCRIPTION
**Pull request by kiennq**
Fix #1894 
It's done by:
- Make `lsp-*-while-no-input` respects `non-essential`
- Return or throw when `body` of `lsp-*-while-no-input` is interrupted by keyboard.
- Use `lsp-completion--last-result` when completion is interrupted by keyboard.

### CODE REVIEW

**Comment by kiennq** [comment]
@dgutov

**Comment by kiennq** [comment]
@yyoncho Can you check if the issue of `company-mode` window flickering is resolved?

**Comment by dgutov** [comment]
Looks good. :+1: 

Let me know if you find any issues with this approach.

**Comment by kiennq** [comment]
@yyoncho

**Comment by yyoncho** [comment]
Sorry for the delay. I tested it and it feels like a huge usability improvement!

Due to the fact that this is one of the most critical components we might consider adding a kill switch for this behavior. How hard will be to do so?

**Review by yyoncho — APPROVED** [review]

**Comment by kiennq** [comment]
> Due to the fact that this is one of the most critical components we might consider adding a kill switch for this behavior. How hard will be to do so?

What do you mean by kill switch?

**Comment by yyoncho** [comment]
A setting that will turn off newly introduced behaviour.

**Comment by kiennq** [comment]
Added `lsp-completion-use-last-result` for that.

**Pull request merged**
