### PR TITLE
feat: Add a solidity language server

### PR DESCRIPTION
**Pull request by Konubinix**
- [X] I added a new entry to [CHANGELOG.md](https://github.com/clojure-lsp/clojure-lsp/blob/master/CHANGELOG.md)

- [X] I updated documentation if applicable (`docs` folder)

### CODE REVIEW

**Comment by Konubinix** [comment]
By looking at the code of lsp-bash.el I realized that I could automate the download of the language server. I did that is a separate commit.

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
LGTM.

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
Thank you for contributing to `lsp-mode`!

**Comment by Konubinix** [comment]
Thank you

-- 
Konubinix
GPG Key    : 7439106A
Fingerprint: 5993 BE7A DA65 E2D9 06CE  5C36 75D2 3CED 7439 106A

**Pull request merged**
