### PR TITLE
[docs] Auto generate settings docs

### PR DESCRIPTION
**Pull request by ericdallo**
- Fix wrong/missing groups on defcustom
- Create missing groups for each feature for easier browsing during customizing the variables and for make it easier to generate the documentation.
- Generate documentation for settings page with all `lsp-*.el` defcustoms.
- Generate documentation for settings page with all `lsp-*.el` deffaces.

Preview 
image

### CODE REVIEW

**Review by yyoncho — APPROVED** [review]
Looks good! What do you think about sorting the items alphabetically?

**Comment by ericdallo** [comment]
@yyoncho you mean the variables/faces?

For the features, I used a specific order, like `Core`, `Completion`, `Diagnostics`...

**Comment by yyoncho** [comment]
> @yyoncho you mean the variables/faces?

Yes. Variables to be sorted under each category.

**Comment by ericdallo** [comment]
Done @yyoncho !

**Comment by yyoncho** [comment]
Thank you!

**Pull request merged**
