### PR TITLE
Add lsp--json-array-use-vector. If set, use default json-array-type vector and use json-parse-string if exists

### PR DESCRIPTION
**Pull request by MaskRay**
https://github.com/emacs-lsp/lsp-mode/issues/210

It works fine with [lsp-ui](https://github.com/emacs-lsp/lsp-ui) + [emacs-ccls](https://github.com/MaskRay/emacs-ccls)

### CODE REVIEW

**Comment by vibhavp** [comment]
While this would definitely move us to use the native JSON API, it would also potentially break other packages that use lsp-mode (other than `lsp-ui` and `ccls`). Adding a client local variable `lsp--client-use-native-json` will help maintain compatibility.

**Comment by MaskRay** [comment]
Added
```
(defcustom lsp--json-array-use-vector nil
  "Use vectors to represent JSON arrays.

If set, native JSON serialization will be used if available.

This option exists to port existing plugins that rely on JSON arrays serialized as lists.
It will be removed and vectors will be used by default in the future."
  :type 'boolean
  :group 'lsp-mode)
```

**Comment by MaskRay** [comment]
Ping?

**Comment by vibhavp** [comment]
Sorry for the late reply, but this would make it a global setting, which would still break some clients. I was suggesting a client-local option for using native JSON, something I tried in this PR: https://github.com/emacs-lsp/lsp-mode/pull/435

**Pull request closed without merging**
