### PR TITLE
Add test for PHP Language Server to check the existence of the php script

### LINKED ISSUE #1123: Incorrect determination of the availability of php-language-server
The default of `lsp-clients-php-server-command` is   `("php" ,(expand-file-name "~/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php"))`, but in lsp-mode.el, its availability is determined by the existence of `php`. In other words, for someone who has php installed but has no interest in lsp for php, this will always lead to a false positive.

I understand that it can be customized out, but it is more like a hack and by default the false positive shouldn't be present for most people who only occasionally opens php files and do not want to set up lsp for php. IMO, the customization should be for someone who installs php-language-server.php in a different location.

This can be reproduced by opening a php file, where `php` is available but `php-language-server.php` is unavailable. `*lsp-log*` buffer shows:

```
Command "intelephense --stdio" is not present on the path.
Command "php /home/hong/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php" is present on the path.
Found the following clients for /home/hong/tmp/a.php: (server-id php-ls, priority -2)
The following clients were selected based on priority: (server-id php-ls, priority -2)
```

### PR DESCRIPTION
**Pull request by xuhdev**
Currently only the existence of the executable, which is likely "php", is checked to determine
whether PHP Language Server is available. This commit adds check for the existence of
php-language-server.php when applicable.

Close #1123

cc @yyoncho @yevgnen

### CODE REVIEW

**Comment by yyoncho** [comment]
This change is breaking the CI byte compilation tests: 

```
In toplevel form:
lsp-clients.el:309:16:Error: reference to free variable ‘lsp-php-server-command’
...............Test lsp-byte-compilation-test backtrace:
```

**Comment by xuhdev** [comment]
Allow me to update this PR? :)

**Comment by yyoncho** [comment]
> Allow me to update this PR? :)

Sorry, that was misclick.

**Comment by xuhdev** [comment]
@yyoncho I've updated the PR. Please review. Thanks!

**Comment by yyoncho** [comment]
Thank you and congrats for your first `lsp-mode` PR!

**Pull request merged**
