### PR TITLE
Add lsp-organize-imports

### PR DESCRIPTION
**Pull request by gexplorer**
Adds support for **organize-imports** command

### CODE REVIEW

**Comment by yyoncho** [comment]
Thanks for the PR! I am unable to find information for this method in lsp spec so I suspect that it might be an extension method. In case it is extension method for a particular server it should be prefixed like lsp-LANGUAGE-organize-imports and moved to the proper file. Can you tell me which language server did you use to test the method or point me to the lsp spec documenting in case I have missed it?

**Comment by gexplorer** [comment]
I did it for the [typescript server](https://github.com/sourcegraph/javascript-typescript-langserver/), based on the same command implementation in tide. I had to add the command to the server which has the pull request pending.

Anyway found the definition of the command in this [specification](https://microsoft.github.io/language-server-protocol/specification), isn't it the official one?

**Comment by yyoncho** [comment]
Yes, it is the official one, I was unable to find `codeActionsProvider`. There is `source.organizeImports` in the spec but I think that it should be implemented through [workspace/executeCommand](https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand)  not by introducing a new method. I am not sure how the server announces that it supports particular CodeActionKind though but I am going to check jdt.ls implementation. I will hold merging this PR untill we sort this out.

**Comment by fjl** [comment]
I need this for Go editing as well.

**Comment by yyoncho** [comment]
@fjl

This method should be moved in lsp-mode from lsp-java 
https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el#L982

If go server supports organize imports it will work.

**Comment by yyoncho** [comment]
Closing in favour of https://github.com/emacs-lsp/lsp-mode/pull/810 .

**Pull request closed without merging**
