### PR TITLE
Add AWK language server support

### PR DESCRIPTION
**Pull request by Hi-Angel**
Implements the following [wishlist item](https://github.com/emacs-lsp/lsp-mode/discussions/2892#discussioncomment-6333173).

### CODE REVIEW

**Review by jcs090218 — APPROVED** [review]
LGTM.

**Comment by Hi-Angel** [comment]
Thank you for reviewing! Given it's been approved, can it be merged? I am waiting for the PR so I can send documentation changes to `awk-language-server` where it would say that `lsp-mode` supports it automatically. I can send now a way to configure it manually, but would be good to avoid sending documentation fixes twice.

**Comment by Hi-Angel** [comment]
Ping

**Review by yyoncho — APPROVED** [review]

**Comment by Hi-Angel** [comment]
Thank you! Sending the docs to `awk-language-server` as well 👍

**Pull request merged**
