### PR TITLE
Add jq-lsp, client for Jq language

### PR DESCRIPTION
**Pull request by nverno**
Add client for Jq language

### CODE REVIEW

**Comment by yyoncho** [comment]
can you fix the conflicts?

**Comment by yyoncho** [comment]
One more thing is missing: can you add your package here: https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L190 so it will be automatically loaded.

**Comment by nverno** [comment]
Ok, I think that does it? Do you want me to squash commits or anything? thanks

**Review by yyoncho — APPROVED** [review]

**Comment by yyoncho** [comment]
It's good. Thank you.

**Pull request merged**
