### PR TITLE
Update ruff-lsp to ruff of Python

### PR DESCRIPTION
**Pull request by ccqpein**
Try to update ruff-lsp to ruff 

related issue: #4451

### CODE REVIEW

**Comment by jcs090218** [comment]
Should we rename the file `lsp-ruff-lsp.el` to `lsp-ruff.el`? 🤔

**Comment by ccqpein** [comment]
@jcs090218 I am ok with that. it makes sense with this PR

**Comment by jcs090218** [comment]
Can you update these following links and description?

- https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-ruff-lsp.el#L1
- https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-ruff-lsp.el#L23
- https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-ruff-lsp.el#L32
- https://github.com/emacs-lsp/lsp-mode/blob/master/mkdocs.yml#L141

We also need to rename all the variables' prefix from `lsp-ruff-lsp` to `lsp-ruff`.

**Comment by ccqpein** [comment]
@jcs090218 Just did. Hopefully I change all of them 😄

**Comment by jcs090218** [comment]
Can you update the CHANGELOG.org as well? Thank you! :D

**Comment by ccqpein** [comment]
@jcs090218 Just did.

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
And this, https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L189. Almost forgot about it. 😅

**Comment by ccqpein** [comment]
@jcs090218 That's ok, you forget much less than I did 😂

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
LGTM! Thank you for your hard work! :D

**Pull request merged**
