### PR TITLE
[Solargraph] Enable diagnostics by default

### LINKED ISSUE #695: Linter errors is not shown with Solargraph
**Describe the bug**
I have enabled lsp-mode and lsp-ui in enh-ruby-mode. The server has started successfully. However linter is not working as I cannot see any warning/error in flycheck. Did I miss something?

**To Reproduce**
1. Enable lsp-mode in enh-ruby-mode
2. Don't see any warning/error in flycheck

**Expected behavior**
See warning/error in flycheck

**Which Language Server did you use**
Solargraph

**OS**
Mac OS 10.14

### PR DESCRIPTION
**Pull request by qhuyduong**
Resolve #695

### CODE REVIEW

**Comment by yyoncho** [comment]
Thank you for the PR!

Do you want to provide settings for all of the options in the server? You may have them in one property like  `lsp-clients-python-settings` or a defcustom for each property `lsp-clients-go--make-init-options`. I think that this will be helpful for the other Ruby users and it will help emacs-lsp team.

**Comment by qhuyduong** [comment]
@yyoncho Yes it's great to have all server options in one place.

**Comment by yyoncho** [comment]
@qhuyduong 

> @yyoncho Yes it's great to have all server options in one place.

Just to make sure we are on the same page, are you going to add all of the settings that are present in the ruby server and create defcustom for them as part of this commit?

**Comment by qhuyduong** [comment]
@yyoncho Yes I'm doing it

**Comment by yyoncho** [comment]
> @yyoncho Yes I'm doing it

Ok, I will wait for all settings before merging the PR.

**Pull request closed without merging**
