### PR TITLE
rust-analyzer updates

### LINKED ISSUE #1330: rust-analyzer: Improve parameter hints
The function [rust-analyzer--update-inlay-hints](https://github.com/rust-analyzer/rust-analyzer/pull/2875/files#diff-45019071aa5c5d2202ef998a6bee0254L210) has to be updated.

### PR DESCRIPTION
**Pull request by flodiebold**
- fix #1330 
 - add runnables support (the one thing that was not yet integrated from the rust-analyzer repo)

### CODE REVIEW

**Comment by brotzeit** [comment]
Nice!

**Comment by brotzeit** [comment]
I have never used runnables. Are there any ressources with some examples that we can link to in the wiki ?

**Comment by flodiebold** [comment]
I don't think there are any resources; even the RA docs just have [one sentence](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/features.md#run). Basically, `lsp-rust-analyzer-run` will let you run the test under the cursor, or the last run test. Admittedly, there's similar functionality in rustic and cargo.el, though rust-analyzer is in a better position to detect tests and give the correct command. (Also, I really like being able to rerun the last test while editing code elsewhere; I don't know if rustic has that.)

**Comment by brotzeit** [comment]
Test arguments are stored in `rustic-test-arguments` and you can rerun the tests with `rustic-cargo-test-rerun`.

**Pull request merged**
