### PR TITLE
Make sure that json server runs for json files even in js-mode

### PR DESCRIPTION
**Pull request by yyoncho**
- introduced `lsp-activate-on` which mimic what vscode does - it selects the
language server based on the language in the file. This will make the language
servers a bit easier to configure and it will give more control to the users via
`lsp-language-id-configuration`.

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]
Nice!

**Comment by yyoncho** [comment]
@alanz - I think that this may help with erlang/elp server selection issue in case the languages are different for both.

**Comment by alanz** [comment]
> I think that this may help with erlang/elp server selection issue in case the languages are different for both.

Thanks, I'll see how it goes when it updates on MELPA

**Review by jcs090218 — APPROVED** [review]

**Comment by kiennq** [comment]
@yyoncho Is there a way to override buffer language from clients (`lsp-json` in this case)?
With this change, the buffer language is fixed into `json` for `.json` files and `jsonc` for `.jsonc` files instead of base on current major modes.
For VSCode `settings.json`, it's language id is `jsonc` instead of `json` so won't we need to let the `lsp-mode` clients to be able to override `lsp-buffer-language` in this case?

**Comment by yyoncho** [comment]
> @yyoncho Is there a way to override buffer language from clients (`lsp-json` in this case)?
> With this change, the buffer language is fixed into `json` for `.json` files and `jsonc` for `.jsonc` files instead of base on current major modes.

json-mode/jsonc-mode can be put before the pattern match.

**Pull request merged**
