### PR TITLE
Revert "Add Nix support in lsp-nix"

### PR DESCRIPTION
**Pull request by leungbk**
Reverts emacs-lsp/lsp-mode#2092

In our latest master branch, @sei40kr was not listed as the primary author of that commit. This is weird since if I visit the commit from the PR link, then he is correctly attributed.

If we can't fix the commit, then we should wait till he updates his own PR.

### CODE REVIEW

**Comment by ericdallo** [comment]
Could you open the revert of the revert so @leungbk ?

**Comment by leungbk** [comment]
> Could you open the revert of the revert so @leungbk ?

I don't understand your request. Do you want me to reopen the earlier PR that you merged?

**Comment by ericdallo** [comment]
@leungbk, do we need to @sei40kr open a new PR with your changes?
I got confused so, why did we need to revert the nix pr?

**Comment by leungbk** [comment]
> @leungbk, do we need to @sei40kr open a new PR with the new nix server?
> I got confused so, why did we need to revert the nix pr?

The issue is that in `git log`, the merged commit on our `master` branch shows up as

```
commit efd8c6e52ad3288907f278a711d6bec1add1aa74
Author: Brian Leung <29217594+leungbk@users.noreply.github.com>
Date:   Tue Aug 18 14:10:04 2020 -0700

    Add Nix support (#2092)
    
    Co-authored-by: Seong Yong-ju <sei40kr@gmail.com>
```

Since @sei40kr wrote most of it, I submitted an amendment of his commit, hoping it would appear in `git log` as something like

```
```

**Comment by leungbk** [comment]
> > @leungbk, do we need to @sei40kr open a new PR with the new nix server?
> > I got confused so, why did we need to revert the nix pr?
> 
> The issue is that in `git log`, the merged commit on our `master` branch shows up as
> 
> ```
> commit efd8c6e52ad3288907f278a711d6bec1add1aa74
> Author: Brian Leung <29217594+leungbk@users.noreply.github.com>
> Date:   Tue Aug 18 14:10:04 2020 -0700
> 
>     Add Nix support (#2092)
>     
>     Co-authored-by: Seong Yong-ju <sei40kr@gmail.com>
> ```
> 
> Since @sei40kr wrote most of it, when I submitted my amendment to his commit, I thought it would appear in `git log` as something like
> 
> ```
> commit efd8c6e52ad3288907f278a711d6bec1add1aa74
> Author: Seong Yong-ju <sei40kr@gmail.com>
> Date:   Tue Aug 18 14:10:04 2020 -0700
> 
>     Add Nix support (#2092)
> ```
> 
> I would prefer to have the latter. When viewing the commit from the page corresponding to the PR I made using @sei40kr's commit, something like this latter version is what shows up.

**Comment by ericdallo** [comment]
I see... well, I don't see any problem in both logs, if @sei40kr sees any problem we can wait for him to rebase the branch otherwise I think we can just merge your PR.
Let's wait a bit more to see if @sei40kr replies here.

**Pull request merged**
