### PR TITLE
remove lsp-clients.el and its references

### PR DESCRIPTION
**Pull request by elxbarbosa**
changes:

- remove lsp-clients.el
- remove lsp-clients-test.el ( javascript and clangd tests extracted)
- remove references in language.md
- remove reference in lsp-haxel

### CODE REVIEW

**Comment by elxbarbosa** [comment]
it will fail :)

**Comment by ericdallo** [comment]
@elxbarbosa there are quite PRs that will have conflicts with each other, maybe we can open an issue to track all these files migration, could you do that? what do you think?

**Comment by ericdallo** [comment]
Maybe something similar to [that](https://github.com/emacs-lsp/lsp-mode/issues/1751)

**Comment by leungbk** [comment]
Why not have every commit in one PR to avoid conflicts?

**Comment by ericdallo** [comment]
It's a way @leungbk, but all the PRs are already created, I think it doesn't worth to rewrite/cherrypick all to a single PR

**Comment by elxbarbosa** [comment]
@ericdallo is that possible? it may be another great oportunity to learn git :)

**Comment by elxbarbosa** [comment]
@leungbk 
lol, never thought that. Anyway,  if you will, let me do the boring part  :)

**Comment by elxbarbosa** [comment]
@ericdallo 
Discussion are in https://github.com/emacs-lsp/lsp-mode/issues/2086

**Pull request merged**
