### PR TITLE
feat: use `name` instead of `description` for bettter readability

### PR DESCRIPTION
**Pull request by Aaronzinhoo**
This is more of a ui-enhancement when working with lsp-yaml

Previously:

image

Updated:
image

Maybe this is more in line with what people see on the schemastore and might be easier to search but I will leave that up to yall.

### CODE REVIEW

**Comment by yyoncho** [comment]
I will let @kiennq decide on that. 

As a side note, you could concat name and description.

**Comment by kiennq** [comment]
Yeah, I'm in the favor of concatenating name + description, perhaps in the format of `"%s (%s)"`.
The name alone is a little bit cryptic sometimes

**Comment by Aaronzinhoo** [comment]
Got it, will make the change!

**Comment by Aaronzinhoo** [comment]
@kiennq @yyoncho updated visual

image

Lemme know if there are any other changes possible!

**Review by kiennq — APPROVED** [review]

**Comment by kiennq** [comment]
Thank you

**Comment by Aaronzinhoo** [comment]
@kiennq glad I could help in some way!

**Pull request merged**
